### ISSUE TITLE
Screenshoots of New Windows Azure Portal

### ISSUE THREAD

**Issue by ananthulasrikar** [hortonworks/data-tutorials#111]
Please Fill in the Following Information before submitting your Issue:

**Tutorial Name**: 
**HDP Version are you Running**:
**Applicable HDP Components**:

**Link to tutorial**(Hortonworks or GitHub website):
### Detailed Description of Issue:

Lot of screenshoots seems to be old azure portal, since the new portal is running
### Proposed Fix:

 I think we can updated the new screenshots :)

**Comment by ananthulasrikar** [comment]
I know its not very important, but beginners get confused.

**Comment by ZacBlanco** [comment]
@ananthulasrikar Can you please specify which tutorial, or provide a link to the tutorial so we know exactly which one to update?

Thanks!

**Comment by patpicos** [comment]
DEPLOYING HORTONWORKS SANDBOX ON MICROSOFT AZURE - All images are now broken :( 
https://hortonworks.com/hadoop-tutorial/deploying-hortonworks-sandbox-on-microsoft-azure/

**Comment by orendain** [comment]
Thanks for pointing this out.  I recently updated the portal screenshots (couple weeks ago), though Hortonworks has deployed a new HDP 2.5 offer, so we'll need more fresh screenshots.  Will tackle this soon 😄

**Comment by orendain** [comment]
Both tutorial copy and screenshots need to be updated for the HDP 2.6.x offering - which has yet to be pushed out.  Need to follow up on the release of the Azure offering before tackling this.

**Comment by gdeleon5** [comment]
@ananthulasrikar Issue has been resolved - thank you for reporting.
