### ISSUE TITLE
Tutorial not updated

### ISSUE THREAD

**Issue by ananthulasrikar** [hortonworks/data-tutorials#112]
Please Fill in the Following Information before submitting your Issue:

**Tutorial Name**: 
**HDP Version are you Running**:
**Applicable HDP Components**:

**Link to tutorial**(Hortonworks or GitHub website):
http://hortonworks.com/hadoop-tutorial/hello-world-an-introduction-to-hadoop-hcatalog-hive-and-pig/
### Detailed Description of Issue:

In the above URL , it has another URL in PRE REQUISITES section pointing to Installing and Configuring the Hortonworks ODBC driver on Windows 7 (http://hortonworks.com/hadoop-tutorial/how-to-install-and-configure-the-hortonworks-odbc-driver-on-windows-7/ ) says its "Deprecated" 
### Proposed Fix:

If the lab work is not needed. Either remove it or keep the new one. I am not sure if I have to go through it for learning or not.

**Comment by orendain** [comment]
Good catch.  In addition, one of the links in the prerequisites section "Installing and Configuring the Hortonworks ODBC driver on Mac OS X" is broken.

**Comment by orendain** [comment]
Resolved, thanks!
