### ISSUE TITLE
Storm Topology Project Missing Dependency

### ISSUE THREAD

**Issue by lestermartin** [hortonworks/data-tutorials#13]
I validated on the 2.3.2 Sandbox (and the emerging 2.4 one) that the http://hortonworks.com/hadoop-tutorial/simulating-transporting-realtime-events-stream-apache-kafka/#section_4 tutorial is missing a dependency (called out in the notes section) and forces a fix as identified about half-way down  https://github.com/HortonworksUniversity/Essentials/blob/master/demos/storm/README.md to get it working.

I was thinking of forking/fixing and creating a pull request, but when I visited https://github.com/hortonworks/tutorials/blob/be9e1a6afd906df2744d6bef6e4a72a5e74e465b/tutorials/hortonworks/realtime-event-processing-with-hadoop/rtep-2.md I found out that the source is actually embedded in a big zip file, not in the tutorials GitHub repo itself.

Unfortunately, https://github.com/search?q=BaseTruckEventTopology.java&type=Code&utf8=%E2%9C%93 actually shows MANY variations of this code from MANY Hortonworkers; bummer.

Ultimately, how should we address this?
- The hack is to just modify the big zip file to have the corrected configuration and rebuilt jars (not terrible solution)
- We could just reword the tutorial to tell folks to add this dependency and rebuild instead of it being optional (lets/forces the reader to see more details)
- Possibly, the ~best~ (and probably the biggest effort) would be to put the source code in this repo and reword the lab to make the build operation a manual step (again, this has the biggest effort I think)
- _Something else I'm not thinking about??_

I'm glad to help resolve this, but want to make sure I know the direction we should be taking to fix it and I wanted to make sure I'm not doing double-duty if someone is already addressing this.

**Comment by abajwa-hw** [comment]
+1 on adding the source to this repo...this had been the direction but seems it did not happen. I had suggested the same when we worked on updating this tutorial for 2.3 but ran out of time before HS and just zipped the code up on dropbox

**Comment by orendain** [comment]
Thanks for the tag.  Update on this issue is a long time coming - the tutorial was completely revamped some time ago, fixing this issue.
