### ISSUE TITLE
Lahman Data File URL is incomplete

### ISSUE THREAD

**Issue by slachterman** [hortonworks/data-tutorials#156]
Please Fill in the Following Information before submitting your Issue:

**Tutorial Name**: Faster Pig With Tez
**HDP Version are you Running**: N/A
**Applicable HDP Components**: N/A

**Link to tutorial**(Hortonworks or GitHub website): http://hortonworks.com/hadoop-tutorial/faster-pig-tez/

**Comment by orendain** [comment]
Thanks for the fix.  Looks like the issue was acknowledged at some point, but it looks like the tutorial has since been deprecated and removed.
