### ISSUE TITLE
Solr UI port should specify 8983

### ISSUE THREAD

**Issue by slachterman** [hortonworks/data-tutorials#161]
Please Fill in the Following Information before submitting your Issue:

**Tutorial Name**: Indexing And Searching Documents With Apache Solr
**HDP Version are you Running**: 2.4
**Applicable HDP Components**: Solr

**Link to tutorial**(Hortonworks or GitHub website): http://hortonworks.com/hadoop-tutorial/searching-data-solr/
### Detailed Description of Issue:

See https://community.hortonworks.com/questions/41056/solr-web-ui-port-discrepancy.html#answer-41220
Port 8984 is specified for Solr web UI but only port 8983 is forwarded for Sandbox.
### Proposed Fix:

Change 8984 to 8983.

**Comment by orendain** [comment]
PR merged a while back, closing issue.
