### ISSUE TITLE
S3 link to Atlas-Ranger TP VM is broken

### ISSUE THREAD

**Issue by slachterman** [hortonworks/data-tutorials#166]
Please Fill in the Following Information before submitting your Issue:

**Tutorial Name**: TAG BASED POLICIES WITH APACHE RANGER AND APACHE ATLAS
**HDP Version are you Running**: 2.4
**Applicable HDP Components**: Atlas, Ranger

**Link to tutorial**(Hortonworks or GitHub website): http://hortonworks.com/hadoop-tutorial/tag-based-policies-atlas-ranger/
### Detailed Description of Issue:

The following S3 URL returns a NoSuchKey error: https://s3.amazonaws.com/demo-drops.hortonworks.com/HDP-Atlas-Ranger-TP.ova
### Proposed Fix:

Provide a corrected link to the HDP-Atlas-Ranger-TP OVA file.

**Comment by orendain** [comment]
Thanks!  Escalated - we're working on it now!

**Comment by orendain** [comment]
Fixed!
