### ISSUE TITLE
Typo in the second paragraph of Introduction in Learning the Ropes of Apache NiFi tutorial

### ISSUE THREAD

**Issue by sfrechette** [hortonworks/data-tutorials#167]
Please Fill in the Following Information before submitting your Issue:

**Introduction**: 
**hdp-2.4.0**:
**LEARNING THE ROPES OF APACHE NIFI**:

**http://hortonworks.com/hadoop-tutorial/learning-ropes-apache-nifi/#section_1
### Detailed Description of Issue: Typo in the text of the tutorial - second paragraph "... for for..." ;

For the purposes of this tutorial, assume that a city planning board is evaluating the need for a new highway. This decision is dependant on current traffic patterns, particularly as other roadwork initiatives are under way. Integrating live data poses a problem because traffic analysis has traditionally been done using historical, aggregated traffic counts. To improve traffic analysis, the city planner wants to leverage real-time data to get a deeper understanding of traffic patterns. NiFi was selected **for for** this real-time data integration.
### Proposed Fix:

Simply remove duplicate **for**

**Comment by orendain** [comment]
Fixed, thanks!
