### ISSUE TITLE
Ranger configuration in screenshot is not correct for use case

### ISSUE THREAD

**Issue by slachterman** [hortonworks/data-tutorials#168]
Please Fill in the Following Information before submitting your Issue:

**Tutorial Name**: SECURING HDFS, HIVE AND HBASE WITH KNOX AND RANGER
**HDP Version are you Running**: HDP 2.4
**Applicable HDP Components**: Ranger, Hive

**Link to tutorial**(Hortonworks or GitHub website): http://hortonworks.com/hadoop-tutorial/manage-security-policy-hive-hbase-knox-ranger/
### Detailed Description of Issue:

Please see [this HCC post](https://community.hortonworks.com/questions/45293/ranger-policy-change-not-affecting-behavior.html).

I do not believe [this screenshot](https://raw.githubusercontent.com/hortonworks/tutorials/hdp/assets/securing-hdfs-hive-hbase-with-knox-ranger/hive-grant-revoke-1.png) is correct. The Delegate Admin checkbox is important in order for it1 to able to grant/revoke permissions (effectively updating the Sandbox_hive policy).

Also, the user network1 should not be included in the configuration of the policy. That user is added by the successful execution of the GRANT command within beeline by the it1 user.
### Proposed Fix:

Fix the screenshot (see [this image](https://www.anony.ws/image/NDQ6), and add text that indicates the importance of the Delegate Admin checkbox. Add _a second screenshot_ that captures the effects of the successful execution of the GRANT command within beeline by the it1 user.

**Comment by orendain** [comment]
Looks like the tutorial was updated, but this issue wasn't referenced/responded to.  Closing this issue, but feel free to reopen if the updates didn't touch on the specific fix proposed.  Thanks!
