### ISSUE TITLE
Table AVG_MILEAGE holds average miles per gallon for each truck, not all trips for each truck

### ISSUE THREAD

**Issue by meed-wiej** [hortonworks/data-tutorials#170]
**Tutorial**: Hello HDP An Introduction to Hadoop with Hive and Pig 
**HDP**: 2.4 

**Link to tutorial**: http://hortonworks.com/hadoop-tutorial/hello-world-an-introduction-to-hadoop-hcatalog-hive-and-pig/#analyze-truck-data
### Detailed Description of Issue:

In section 2.6.7 "LOAD SAMPLE DATA OF AVG_MILEAGE" the last sentence of the first paragraph is:

_You see our table is now a list of each trip made by a truck._

That's not correct. The AVG_MILEAGE table contains the average miles per gallon for each truck.
### Proposed solution:

Fix the sentence:

_You see our table is now a list of average miles per gallon for each truck._

**Comment by orendain** [comment]
Good catch, we're on it!  @gdeleon5

**Comment by orendain** [comment]
Resolved, thanks!
