### ISSUE TITLE
Create Tag and tag based policies

### ISSUE THREAD

**Issue by HItesh1809** [hortonworks/data-tutorials#177]
Please Fill in the Following Information before submitting your Issue:

**Create Tag and Tag Based policies**: 
**HDP Version- 2.5**:
**Atlas and Ranger**:

**Link to tutorial**(Hortonworks or GitHub website):
After creating Tag based policy when user raj_ops try's to access table in Hive_view he should be denied but he was allowed. I mean tags where created only for ssn and location column and he tried to access all column so he should be denied but he wasn't. Can anyone explain me that part?

**Comment by orendain** [comment]
@HItesh1809 Heya, which tutorial is this referencing?  You may get a quicker response by posting on Hortonworks Community Connection (by following the link at the bottom of the tutorial).  Closing this issue just because of the date it was posted, but feel free to open for any followup 😃
