### ISSUE TITLE
Provide hortonworks-sandbox-hdp2.5-guide/start_sandbox.psi ?

### ISSUE THREAD

**Issue by JimSEOW** [hortonworks/data-tutorials#179]
Please provide powershell version of 
tutorials/tutorials/hortonworks/hortonworks-sandbox-hdp2.5-guide/start_sandbox.sh 
# for [PowerShell for Windows 10](https://docs.docker.com/docker-for-windows/) for docker

This step is fine in PowerShell 
`docker run -v hadoop:/hadoop --name sandbox --hostname "sandbox.hortonworks.com" --privileged -d -p 6080:6080 -p 9090:9090 -p 9000:9000 -p 8000:8000 -p 8020:8020 -p 42111:42111 -p 10500:10500 -p 16030:16030 -p 8042:8042 -p 8040:8040 -p 2100:2100 -p 4200:4200 -p 4040:4040 -p 8050:8050 -p 9996:9996 -p 9995:9995 -p 8080:8080 -p 8088:8088 -p 8886:8886 -p 8889:8889 -p 8443:8443 -p 8744:8744 -p 8888:8888 -p 8188:8188 -p 8983:8983 -p 1000:1000 -p 1100:1100 -p 11000:11000 -p 10001:10001 -p 15000:15000 -p 10000:10000 -p 8993:8993 -p 1988:1988 -p 5007:5007 -p 50070:50070 -p 19888:19888 -p 16010:16010 -p 50111:50111 -p 50075:50075 -p 50095:50095 -p 18080:18080 -p 60000:60000 -p 8090:8090 -p 8091:8091 -p 8005:8005 -p 8086:8086 -p 8082:8082 -p 60080:60080 -p 8765:8765 -p 5011:5011 -p 6001:6001 -p 6003:6003 -p 6008:6008 -p 1220:1220 -p 21000:21000 -p 6188:6188 -p 61888:61888 -p 2222:22 sandbox /usr/sbin/sshd -D`

This step is not all OK
`docker exec -t sandbox make --makefile /usr/lib/hue/tools/start_scripts/start_deps.mf -B Startup -j -i`
![picture1](https://cloud.githubusercontent.com/assets/8244633/19233662/3d07af8a-8ee7-11e6-85ba-6a08f963f335.png)

If I run this script (Which was uncommented in start_sandbox.sh),`docker exec -t sandbox /etc/init.d/startup_script start`   [I understand that this step is the same for: Run [notes for Mac users](http://hortonworks.com/hadoop-tutorial/hortonworks-sandbox-guide/#section_4)], the output is similar to that as expected for the Mac

![powershell_2016-10-10_12-48-14](https://cloud.githubusercontent.com/assets/8244633/19233772/f0988812-8ee7-11e6-8014-7061a8917d31.png)

When I access the localhost:8888, it seems to works
![brave_2016-10-10_12-56-21](https://cloud.githubusercontent.com/assets/8244633/19233945/068a23fa-8ee9-11e6-89f3-5aa54b2b42aa.png)

==> **Do I miss any extra configuration** by using the _uncommented script_ ?<===
`docker exec -t sandbox /etc/init.d/startup_script start`

**Comment by orendain** [comment]
There are currently 2 pull requests out for this:

#212, which uses https://raw.githubusercontent.com/szantopeter/tutorials/139ff4932d5ce1a41a25f477162ad6f78b5eb7d7/tutorials/hortonworks/hortonworks-sandbox-hdp2.5-guide/start_sandbox.ps1

and

#188, which uses
https://raw.githubusercontent.com/jpdias/tutorials/c09a510e173a746f4d3833c6b251845b239ead56/tutorials/hortonworks/hortonworks-sandbox-hdp2.5-guide/start_sandbox.ps1

We should decide on one (or a combination) and introduce it into the new branch.   I included references to the files above so as to keep the source around after the PR cleanup.

**Comment by gdeleon5** [comment]
@JimSEOW Thank you for opening issue and using Hortonworks Sandbox.

The [Hortonworks Data Platform (HDP) 2.6.4](https://hortonworks.com/downloads/#sandbox) is now available.
Additionally, the [Sandbox Deployment and Install Guide for Docker](https://hortonworks.com/tutorial/sandbox-deployment-and-install-guide/section/3/) and startup scripts  have been updated.

If you continues having issues, please don't hesitate to re-open or create new issue.
