### ISSUE TITLE
Wrong folder name specified from where the CSV file is imported into Hive

### ISSUE THREAD

**Issue by shankarps** [hortonworks/data-tutorials#184]
Please Fill in the Following Information before submitting your Issue:

**Tutorial Name**: HADOOP TUTORIAL – GETTING STARTED WITH HDP
**HDP Version are you Running**: HDP2.5
**Applicable HDP Components**: Apache Hive, Apache HDFS

**Link to tutorial**(Hortonworks or GitHub website): https://github.com/hortonworks/tutorials/blob/hdp-2.5/tutorials/hortonworks/hello-hdp-an-introduction-to-hadoop/hello-hdp-section-4.md 
AND
https://github.com/hortonworks/tutorials/blob/hdp/tutorials/hortonworks/hello-hdp-an-introduction-to-hadoop/hello-hdp-section-3.md

### Detailed Description of Issue:

In Lab 1 (Loading Sensor Data into HDFS), the tutorial loads the trucks.csv file in the /tmp/maria_dev/data folder. But in Lab 2 (Hive - Data ETL) the tutorial instructs the learner to import the trucks.csv file from the  "/user/maria_dev/data/" folder.  This is misleading and will not work.

### Proposed Fix:
In Lab 2, change the screenshots and description to import the trucks.csv file from the "/tmp/maria_dev/data" folder.

**Comment by mdeguzis** [comment]
This should already be fixed. Lab 1 notes:

> Navigate to /user/maria_dev directory by clicking on the directory links.

Data is not being loaded into /tmp

**Comment by orendain** [comment]
Closing issue as it seems it's resolved.  Feel free to reopen if that's not the case 😄
