### ISSUE TITLE
Build_tutorials.sh script "id" issue 

### ISSUE THREAD

**Issue by james94** [hortonworks/data-tutorials#19]
Problem: I just came across a problem when uploading the hello hdp tutorials onto the website. I can't navigate to different labs 1 - 6.
- generates duplicate id's

For hello hdp, the pages are connected all on one page, it's just the javascript creates the allusion that they are separate pages. Therefore, lab 1 having the div tag below and lab 2 also having that tag creates a duplicate. 

example:

<div id="tutorial-content"></div>

Our script works well for one page tutorials. Have we accounted for tutorials like hello hdp in the script code?
@ZacBlanco @roberthryniewicz

**Comment by ZacBlanco** [comment]
@james94 because we use jekyll to build the scripts we can add metadata -- specifically YAML frontmatter -- to each tutorial which can aid us in the automation of the process when converting the tutorials to HTML

I will elaborate more on this in the future

**Comment by ZacBlanco** [comment]
@james94  please see #44 and let me know your feedback

**Comment by ZacBlanco** [comment]
@james94  If this is not and issue still can you please close it

**Comment by james94** [comment]
Hey Zac. My Apologies for not responding to your message sooner. The problem still occurs with the duplicate id's across two labs. I will include two images, section 2 and section 3 from hello hdp, with blue boxes that surround a duplicate id. Have you come across this?
![duplicate_id_hello_hdp_section2](https://cloud.githubusercontent.com/assets/11840449/14898908/36a213a4-0d3e-11e6-88dd-626ca343420f.png)
![duplicate_id_hello_hdp_section3](https://cloud.githubusercontent.com/assets/11840449/14898909/36a6b2ce-0d3e-11e6-9e66-318b37b8f804.png)

@ZacBlanco

**Comment by orendain** [comment]
Meant to remove priority tag and reassign, but looks like issue is resolved.  Closing.
