### ISSUE TITLE
Password for user 'hive' ?

### ISSUE THREAD

**Issue by mdeguzis** [hortonworks/data-tutorials#193]
Please Fill in the Following Information before submitting your Issue:

**Tutorial Name**:  Hello HDP section 4, Lab 2
**HDP Version are you Running**: 2.5.0
**Applicable HDP Components**: SSH/Hive

**Link to tutorial**(Hortonworks or GitHub website):

https://github.com/hortonworks/tutorials/blob/hdp-2.5/tutorials/hortonworks/hello-hdp-an-introduction-to-hadoop/hello-hdp-section-4.md

### Detailed Description of Issue:

Section 2.2.10 Beeline - Command Shell notes:

```
i. Local Sandbox VM Open up shell in the box to ssh into HDP with

ssh maria_dev@127.0.0.1 -p 2222 maria_dev (which is wrong, PR #191 submitted)

ii. su hive

iii. beeline Starts Beeline shell and now you can enter commands and SQL

iv. quit; Exits out of the Beeline shell.
```

However, there is no mention of what the 'hive' password is. `beeline` can also be executed just fine as user 'maria_dev'. However, any command doesn't present feedback, so I suspect 'maria_dev' lacks some permissions then. This section should provide at least one SQL command example after connecting to hive.

If you are going to leave out any example beeline commands, the 'su hive' part should be fixed.

### Proposed Fix:

Provide an example set of commands (1 or both).

In one shot:

```
beeline -u jdbc:hive2://localhost:10000 -n maria_dev
Connecting to jdbc:hive2://localhost:10000
Connected to: Apache Hive (version 1.2.1000.2.5.0.0-1245)
Driver: Hive JDBC (version 1.2.1000.2.5.0.0-1245)
Transaction isolation: TRANSACTION_REPEATABLE_READ
Beeline version 1.2.1000.2.5.0.0-1245 by Apache Hive
0: jdbc:hive2://localhost:10000> 
```

2 part (preferred as it uses beeline prompt)t:

```
[maria_dev@sandbox ~]$ beeline
Beeline version 1.2.1000.2.5.0.0-1245 by Apache Hive
beeline> show tables;
No current connection
beeline> !connect jdbc:hive2://localhost:10000 maria_dev
Connecting to jdbc:hive2://localhost:10000
Enter password for jdbc:hive2://localhost:10000: *********
Connected to: Apache Hive (version 1.2.1000.2.5.0.0-1245)
Driver: Hive JDBC (version 1.2.1000.2.5.0.0-1245)
Transaction isolation: TRANSACTION_REPEATABLE_READ
0: jdbc:hive2://localhost:10000> 
```
A simple "show tables" can be thrown in for a quick look at the interface.
Also, `quit` does not work with beeline>. You must use ``. After the JDBC connect is made, you must issue `!exit` or `!quit`.

```
beeline> quit;
No current connection

# proper command
!quit
```

**Comment by orendain** [comment]
PR #191, hitting on the password/auth issue, was merged.

@gdeleon5 is working on the proposed Beeline changes.

Thanks!

**Comment by orendain** [comment]
For reference, the latest version of that tutorial: https://github.com/hortonworks/data-tutorials/blob/hdp-2.5/tutorials/hortonworks/hello-hdp-an-introduction-to-hadoop/hello-hdp-section-4.md

**Comment by orendain** [comment]
Resolved, thanks!
