### ISSUE TITLE
Ambari Welcome URL does not exist

### ISSUE THREAD

**Issue by mandolyte** [hortonworks/data-tutorials#195]
Please Fill in the Following Information before submitting your Issue:

**Tutorial Name**: Learning the Ropes of the Hortonworks Sandbox
**HDP Version are you Running**: 2.5
**Applicable HDP Components**: Ambari

**Link to tutorial**(Hortonworks or GitHub website): http://hortonworks.com/hadoop-tutorial/learning-the-ropes-of-the-hortonworks-sandbox/

### Detailed Description of Issue:
Section 2.3 states "Enter the Ambari Welcome URL and then you should see a similar screen". However, there is no mention in the page for this URL. The list of links in Section 2.1 under the heading "Services provided by the sandbox" do not include a link to an Ambari Welcome Page. The screen shot show is actually the Manage Ambari screen.

### Proposed Fix:
Change the statement to:  "Enter the Manage Ambari URL and then you should see a similar screen"

**Comment by gdeleon5** [comment]
Issue resolved - thank you for reporting.
