### ISSUE TITLE
Sample command lines for scp are inaccurate

### ISSUE THREAD

**Issue by wasphub** [hortonworks/data-tutorials#199]
Please Fill in the Following Information before submitting your Issue:

**Tutorial Name**: 
Learning the ropes

**HDP Version are you Running**:
2.4

**Applicable HDP Components**:

**Link to tutorial**(Hortonworks or GitHub website):
http://hortonworks.com/hadoop-tutorial/learning-the-ropes-of-the-hortonworks-sandbox/

### Detailed Description of Issue:
The `scp` sample commands are not accurate. I'm using the Azure image, and I'm a Windows developer, so not that used to linux-based commands, therefore it took me a bit to figure out that in a line like

    scp -P 2222 ~/Downloads/HDF-1.2.0.1-1.tar.gz james94@localhost:/james94

there are at least a couple of inaccuracies.

### Proposed Fix:

- change the port number, it's not **2222** but **22**
- the folder `/james94` would not exist, whatever the user name is, it should say `/home/james94`, or more simply just `~`

**Comment by Castro38** [comment]
Thank you for reporting this issue, the tutorial has been modified significantly. If there is any other issues please continue reporting issues.
