### ISSUE TITLE
Missing "table" keyword for "show create".

### ISSUE THREAD

**Issue by Shaulian** [hortonworks/data-tutorials#203]
Please Fill in the Following Information before submitting your Issue:

**Tutorial Name**: HADOOP TUTORIAL – GETTING STARTED WITH HDP
**HDP Version are you Running**: 2.5
**Applicable HDP Components**: Hive

**Link to tutorial**(Hortonworks or GitHub website): https://github.com/hortonworks/tutorials/blob/hdp-2.5/tutorials/hortonworks/hello-hdp-an-introduction-to-hadoop/hello-hdp-section-4.md#227-sample-data-from-the-trucks-table

### Detailed Description of Issue:
Missing "table" keyword when wishing to get a create table DDL.

### Proposed Fix:
Add "table" keyword to the "show create {table_name};" before the curly brackets.

**Comment by Shaulian** [comment]
How do I become a contributor? I'm not able to push new branches to origin. 
Please help.

**Comment by orendain** [comment]
Successfully merged in the pull request you submitted, thanks!
