### ISSUE TITLE
DEPLOYING HORTONWORKS SANDBOX ON MICROSOFT AZURE

### ISSUE THREAD

**Issue by patpicos** [hortonworks/data-tutorials#209]
Please Fill in the Following Information before submitting your Issue:

**Tutorial Name**:  DEPLOYING HORTONWORKS SANDBOX ON MICROSOFT AZURE

**Link to tutorial**(Hortonworks or GitHub website):
https://hortonworks.com/hadoop-tutorial/deploying-hortonworks-sandbox-on-microsoft-azure/

### Detailed Description of Issue:
All image links broken

**Comment by orendain** [comment]
Fixed, thanks!
