### ISSUE TITLE
Leveraging Apache Falcon with Your Hadoop Clusters - deprecated commands

### ISSUE THREAD

**Issue by patpicos** [hortonworks/data-tutorials#210]
Please Fill in the Following Information before submitting your Issue:

**Tutorial Name**: 
Tutorial Name: Leveraging Apache Falcon with Your Hadoop Clusters

HCC Tutorial Tag: tutorial-670 and hdp-2.5.0

**HDP Version are you Running**:
**Applicable HDP Components**:

**Link to tutorial**(Hortonworks or GitHub website):

### Detailed Description of Issue:
hadoop fs is deprecated

### Proposed Fix:
change to hdfs dfs

**Comment by orendain** [comment]
Fixed, thanks!

For reference, notice of the deprecation: https://hadoop.apache.org/docs/r2.6.0/hadoop-project-dist/hadoop-common/CommandsManual.html#fs
