### ISSUE TITLE
Mirroring Datasets Between Hadoop Clusters with Apache Falcon - membership error

### ISSUE THREAD

**Issue by patpicos** [hortonworks/data-tutorials#211]
Please Fill in the Following Information before submitting your Issue:

Tutorial Name: Mirroring Datasets Between Hadoop Clusters with Apache Falcon

HCC Tutorial Tag: tutorial-680 and hdp-2.5.0

**HDP Version are you Running**: 2.4.1 Ambari
**Applicable HDP Components**: Ambari

**Link to tutorial**(Hortonworks or GitHub website):

### Detailed Description of Issue:
when creating ambari-qa and trying to add membership, i get the following error:
users.alert.cannotAddUser
An internal system exception occurred: Group views doesn't exist

**Comment by orendain** [comment]
You may want to post on HCC for a quicker, more direct, response.  Here's a direct link to posting a question with tags for that tutorial: https://community.hortonworks.com/questions/ask.html?space=81&topics=tutorial-680&topics=hdp-2.5.0

Hope that helps!  Closing the issue, feel free to reopen for any followup.
