### ISSUE TITLE
Hbase tutorial - 404 not found when trying to download data.csv file

### ISSUE THREAD

**Issue by cmstudent** [hortonworks/data-tutorials#216]
**Tutorial name**: Introduction to Apache HBase Concepts, Apache Phoenix and New Backup & Restore Utility in HBase
**Platform version**: HDP 2.5
**Link to tutorial**: https://hortonworks.com/hadoop-tutorial/introduction-apache-hbase-concepts-apache-phoenix-new-backup-restore-utility-hbase/

### Description of issue:
Issue is on this step. 4. DATA MANIPULATION COMMANDS IN HBASE

Is the link updated? Im getting a "404 not found" when I try to access or import the data.csv file. 
https://raw.githubusercontent.com/hortonworks/tutorials/hdp/assets/data.csv

**Comment by orendain** [comment]
@cmstudent Fixed - thanks!
