### ISSUE TITLE
Error downloading Lab1-NiFi-Learn-Ropes.xml for NiFi Tutorial

### ISSUE THREAD

**Issue by letssamu** [hortonworks/data-tutorials#221]
**Tutorial name**: ANALYZE TRAFFIC PATTERNS WITH APACHE NIFI
TUTORIAL 1: BUILD A SIMPLE NIFI DATAFLOW
INTRODUCTION

**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**: https://es.hortonworks.com/hadoop-tutorial/learning-ropes-apache-nifi/#section_4

### Description of issue: Link to download "Lab1-NiFi-Learn-Ropes.xml" doesn't work
https://raw.githubusercontent.com/hortonworks/tutorials/hdp/assets/learning-ropes-nifi-lab-series/lab1-template/Lab1-NiFi-Learn-Ropes.xml

**Comment by orendain** [comment]
Fixed, thanks!
