### ISSUE TITLE
airline data file missing and link broken

### ISSUE THREAD

**Issue by johnwhitmore** [hortonworks/data-tutorials#228]
**Tutorial name**: Predicting airline delays using Spark R
**Platform version**: HDP 2.5
**Link to tutorial**: https://hortonworks.com/hadoop-tutorial/predicting-airline-delays-using-sparkr/

**Comment by orendain** [comment]
Great catch - proposed fix sounds good.  I'll get a PR up tonight

**Comment by orendain** [comment]
Thanks @johnwhitmore - updated! https://hortonworks.com/hadoop-tutorial/predicting-airline-delays-using-sparkr/
