### ISSUE TITLE
Lab 4 Spark Risk Factor has a few errors that prevent completion of the tutorial

### ISSUE THREAD

**Issue by Jaraxal** [hortonworks/data-tutorials#236]
**Tutorial name**: Lab 4: Spark - Risk Factor
**Platform version**: HDP 2.6
**Link to tutorial**: https://github.com/hortonworks/data-tutorials/blob/master/tutorials/hdp/hdp-2.5/hadoop-tutorial-getting-started-with-hdp/tutorial-5.md

### Description of issue:
The tutorial has you delete the riskfactor table and then says to recreate it using the DDL from the previous tutorial.  This conflicts with a later step in the tutorial which creates the table using a select statement.  The later step will fail with an error.

The create table statement in 4.5.1 uses double for the totmiles field, but it should be a bigint.  Otherwise the insert will fail.

### Proposed fix (if any):
Remove statement about recreating the riskfactor table.
Update create table statement to change totmiles to bigint.

I'll make the changes and create a pull request.

**Comment by orendain** [comment]
@Jaraxal Awesome catches!
