### ISSUE TITLE
Lab 3 Pig Risk Factor tutorial fails because totmiles should be bigint instead of double

### ISSUE THREAD

**Issue by Jaraxal** [hortonworks/data-tutorials#238]
**Tutorial name**: Lab 3 Pig - Risk Factor
**Platform version**: HDP 2.6
**Link to tutorial**: https://github.com/hortonworks/data-tutorials/blob/master/tutorials/hdp/hdp-2.5/hadoop-tutorial-getting-started-with-hdp/tutorial-4.md

### Description of issue:
The create table statement for riskfactor uses double for the totmiles field.  This will cause the tutorial to fail later as it needs to be a bigint.

### Proposed fix (if any):
Change create table statement for riskfactor totmiles from double to bigint.
I'll create a pull request to fix.

**Comment by orendain** [comment]
@Jaraxal Awesome catches!
