### ISSUE TITLE
Mirroring

### ISSUE THREAD

**Issue by mikhilnagarale** [hortonworks/data-tutorials#241]
**Tutorial name**: MIRRORING DATASETS BETWEEN HADOOP CLUSTERS WITH APACHE FALCON
**Platform version**: HDP 2.5
**Link to tutorial**: https://hortonworks.com/hadoop-tutorial/mirroring-datasets-between-hadoop-clusters-with-apache-falcon/

### Description of issue:
I created job for mirroring. Job is successfully triggered in oozie still it's not moving data between clusters.

**Comment by orendain** [comment]
Heya @mikhilnagarale,  I'd suggest posting a question about this using the tutorial-specific tag on HCC (https://community.hortonworks.com/topics/tutorial-680.htm).  Here's a direct link for convenience: https://community.hortonworks.com/questions/ask.html?space=81&topics=tutorial-680&topics=hdp-2.5.0
