### ISSUE TITLE
NIFI : There is no easy way to cleanup Template instance from Canvas once created 

### ISSUE THREAD

**Issue by ashwini47** [hortonworks/data-tutorials#294]
**Tutorial name**:  ANALYZE TRAFFIC PATTERNS WITH APACHE NIFI  TUTORIAL 2: ENRICH SIMPLE DATAFLOW VIA PLACES API
**Platform version**: HDF 2.2, 
**Link to tutorial**: https://hortonworks.com/hadoop-tutorial/learning-ropes-apache-nifi/#section_5

### Description of issue:
In this tutorial is suggest "1. Download the Tutorial-2-enrich-flow-via-places-api.xml template file. Then import the template file into NiFi."

But because we completed previous template so that is already there and this become a new on on the top, 

There is not easy way to cleanup Template instance from Canvas once created 

### Proposed fix (if any):
Please update tutorial how to clear an existing template instance from canvas

**Comment by james94** [comment]
@ashwini47 
Hello,

I added new steps in each "Import section" within every module of this tutorial that covers how to cleanup a previous template, so you can import a new template without the old one overlapping.

For brief explanation, to clear an entire nifi dataflow, press "ctrl + A", the entire flow will be highlighted and you can press delete to remove that dataflow. If any of the queues are loaded with data, you must empty them first, then nifi will allow you to delete the entire dataflow.
