### ISSUE TITLE
Broken Images Tutorial   tutorial-240 and HDP-2.4  

### ISSUE THREAD

**Issue by ashwini47** [hortonworks/data-tutorials#295]
**Tutorial name**:  Processing streaming data in Hadoop with Apache Storm
**Platform version**: HDP-2.6
**Link to tutorial**: https://hortonworks.com/hadoop-tutorial/processing-streaming-data-near-real-time-apache-storm/

### Description of issue:
404: Not Found

**Comment by gdeleon5** [comment]
@ashwini47 The tutorial you had issues with has been deprecated and replaced with [Realtime Event Processing in Hadoop with NiFi, Kafka, and Storm](https://hortonworks.com/tutorial/realtime-event-processing-in-hadoop-with-nifi-kafka-and-storm/).

Check out the tutorial. If you run into issue, please report. Thank You!

**Comment by gdeleon5** [comment]
@ashwini47 I stand corrected - this tutorial was not deprecated. I'm re-opening issue.

**Comment by orendain** [comment]
The link in question was indeed updated to point to the new version of the documentation.  It should be forwarding to: [Realtime Event Processing in Hadoop with NiFi, Kafka and Storm](https://hortonworks.com/tutorial/realtime-event-processing-in-hadoop-with-nifi-kafka-and-storm/)
