### ISSUE TITLE
404 - Link To Traffic Location Data Broken

### ISSUE THREAD

**Issue by fakd23** [hortonworks/data-tutorials#299]
**Tutorial name**: ANALYZE TRAFFIC PATTERNS WITH APACHE NIFI
**Platform version**: HDF 2.1
**Link to tutorial**: https://de.hortonworks.com/hadoop-tutorial/learning-ropes-apache-nifi/#section_3

### Description of issue:
Link to trafficLocs_data_for_simulator.zip broken (https://github.com/hortonworks/data-tutorials/raw/master/tutorials/hdf/hdf-2.1/analyze-traffic-pattern-with-apache-nifi/assets/trafficLocs_data_for_simulator.zip)

### Proposed fix (if any):
replace link in scripts with https://github.com/hortonworks/data-tutorials/blob/master/tutorials/hdf/analyze-traffic-pattern-with-apache-nifi/assets/trafficLocs_data_for_simulator.zip?raw=true

**Comment by gdeleon5** [comment]
Significant updates have been made to tutorial. If issue still persists, please re-open issue.

Thank you for reporting issues.
