### ISSUE TITLE
wrong url for wget

### ISSUE THREAD

**Issue by saptak** [hortonworks/data-tutorials#307]
**Tutorial name**: <Add tutorial name here>
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**: <Either a Hortonworks link or GitHub link works fine>

### Description of issue:
For the wget command the url is incorrect

### Proposed fix (if any):
This is the command you should use:

wget https://github.com/hortonworks/data-tutorials/raw/master/tutorials/hdp/analyzing-social-media-and-customer-sentiment-with-apache-nifi-and-hdp-search/assets/default.json

**Comment by gdeleon5** [comment]
Tutorial has been updated. Thank you for reporting issue.
