### ISSUE TITLE
404 - Link to "Learning the Ropes of the Hortonworks Sandbox" broken

### ISSUE THREAD

**Issue by roamer7038** [hortonworks/data-tutorials#317]
**Tutorial name**: hadoop-tutorial-getting-started-with-hdp
**Platform version**: HDP 2.6
**Link to tutorial**: https://github.com/hortonworks/data-tutorials/blob/master/tutorials/hdp/hadoop-tutorial-getting-started-with-hdp/tutorial-0.md and more, other tutorial-1..8.md

### Description of issue:
Link to "Learning the Ropes of the Hortonworks Sandbox" broken (https://hortonworks.com/tutorial/learning-the-ropes-of-the-hortonworks-sandbox/)

### Proposed fix (if any):
replace link in scripts with https://hortonworks.com/hadoop-tutorial/learning-the-ropes-of-the-hortonworks-sandbox/

**Comment by gdeleon5** [comment]
Thank you for reporting - issue resolved.
