### ISSUE TITLE
Incorrect host names throughout

### ISSUE THREAD

**Issue by TheBellman** [hortonworks/data-tutorials#323]
**Tutorial name**: Realtime Event Processing in Hadoop with NiFi, Kafka and Storm
**Platform version**: HDF 3.0
**Link to tutorial**: https://hortonworks.com/tutorial/realtime-event-processing-in-hadoop-with-nifi-kafka-and-storm/section/2/

### Description of issue:
The materials associated with this tutorial, and the text of the tutorial itself, consistently misname the hostname for the sandbox, using `sandbox.hortonworks.com` whereas the hostname in the sandbox is `sandbox-hdf.hortonworks.com`

### Proposed fix (if any):
All assets for the tutorial, and the text of the tutorial, should be reviewed and updated to match the content of the shipped sandbox .OVA and Docker image

**Comment by james94** [comment]
Hello @TheBellman , this tutorial "realtime event processing in hadoop with NiFi, Kafka and Storm" will be redirected to "https://hortonworks.com/tutorial/real-time-event-processing-in-nifi-sam-schema-registry-and-superset/". The tutorial provided in the link uses a newer version of the Trucking IoT reference application. Please refer to this newer tutorial. It uses the HDF sandbox hostname.
