### ISSUE TITLE
404 on IoT_Lab_Series_DataFlow.xml

### ISSUE THREAD

**Issue by TheBellman** [hortonworks/data-tutorials#324]
**Tutorial name**: Realtime Event Processing in Hadoop with NiFi, Kafka and Storm
**Platform version**: HDF 3.0
**Link to tutorial**: https://hortonworks.com/tutorial/realtime-event-processing-in-hadoop-with-nifi-kafka-and-storm/section/3/

### Description of issue:
The tutorial points to the (non-existent) template at <https://raw.githubusercontent.com/james94/tutorials/hdp/assets/realtime-event-processing-with-hdf/IoT_Lab_Series_DataFlow.xml>

It appears that the template is actually at <https://github.com/hortonworks/data-tutorials/tree/master/tutorials/hdf/realtime-event-processing-in-hadoop-with-nifi-kafka-and-storm/assets>

### Proposed fix (if any):
Correct the link!

**Comment by james94** [comment]
Hello guys, this tutorial "realtime event processing in hadoop with NiFi, Kafka and Storm" will be redirected to "https://hortonworks.com/tutorial/real-time-event-processing-in-nifi-sam-schema-registry-and-superset/". The tutorial provided in the link uses a newer version of the Trucking IoT reference application. Please refer to this newer tutorial. You will find when you deploy the latest HDF sandbox, it comes preloaded with the NiFi DataFlow template for the trucking iot ref application.
