### ISSUE TITLE
Incorrect value in RouteOnContent configuration

### ISSUE THREAD

**Issue by TheBellman** [hortonworks/data-tutorials#325]
**Tutorial name**: Realtime Event Processing in Hadoop with NiFi, Kafka and Storm
**Platform version**: HDF 3.0
**Link to tutorial**: https://hortonworks.com/tutorial/realtime-event-processing-in-hadoop-with-nifi-kafka-and-storm/section/3/

### Description of issue:
In step 4, configuring the RouteOnContent processor, the value to provide for `search_for_truck_event_data` is display as "`(Normal)" - this does not correspond to what is suggested by the image immediately below which indicates a much broader set of strings to look for. 

### Proposed fix (if any):
Based on the contents of the two event type Enums in `com.hortonworks.streaming.impl.domain`, the required set of values is:
`(Hard Braking)|(Lane Departure)|(Normal)|(Overspeed)|(Swerving)|(Unsafe following distance)|(Unsafe tail distance)`

**Comment by jf61975** [comment]
it works.
thanks soooooooo much. 
every issue you posted for the tutorial of NIFI helps me to figure out my puzzle.

**Comment by james94** [comment]
Hello @TheBellman @jf61975 , this tutorial "realtime event processing in hadoop with NiFi, Kafka and Storm" will be redirected to "https://hortonworks.com/tutorial/real-time-event-processing-in-nifi-sam-schema-registry-and-superset/". The tutorial provided in the link uses a newer version of the Trucking IoT reference application. Please refer to this newer tutorial.
