### ISSUE TITLE
Incorrect filename specification in UpdateAttribute processor

### ISSUE THREAD

**Issue by TheBellman** [hortonworks/data-tutorials#326]
**Tutorial name**: Realtime Event Processing in Hadoop with NiFi, Kafka and Storm
**Platform version**: HDF 3.0
**Link to tutorial**: https://hortonworks.com/tutorial/realtime-event-processing-in-hadoop-with-nifi-kafka-and-storm/section/3/

### Description of issue:
Section 3.3, where the UpdateAttribute processor is configured specifies `{UUID()}` instead of `${UUID()}`

### Proposed fix (if any):
Correct the value.

**Comment by james94** [comment]
Hello @TheBellman , this tutorial "realtime event processing in hadoop with NiFi, Kafka and Storm" will be redirected to "https://hortonworks.com/tutorial/real-time-event-processing-in-nifi-sam-schema-registry-and-superset/". The tutorial provided in the link uses a newer version of the Trucking IoT reference application. Please refer to this newer tutorial. The problem you were running into before should be resolved.
