### ISSUE TITLE
Storm View not present by default in Sandbox

### ISSUE THREAD

**Issue by TheBellman** [hortonworks/data-tutorials#327]
**Tutorial name**: REALTIME EVENT PROCESSING IN HADOOP WITH NIFI, KAFKA AND STORM
**Platform version**: HDF 3.0
**Link to tutorial**: https://hortonworks.com/tutorial/realtime-event-processing-in-hadoop-with-nifi-kafka-and-storm/section/5/

### Description of issue:
Section 2.1, " VERIFY KAFKA IS RUNNING & DEPLOY TOPOLOGY" advises the user to open the Storm View in Ambari - by default in the sandbox this is not available and needs to be created.

### Proposed fix (if any):
Add information to the page advising how to set up the Storm view

**Comment by james94** [comment]
Hello @TheBellman , this tutorial "realtime event processing in hadoop with NiFi, Kafka and Storm" will be redirected to "https://hortonworks.com/tutorial/real-time-event-processing-in-nifi-sam-schema-registry-and-superset/". The tutorial provided in the link uses a newer version of the Trucking IoT reference application. Please refer to this newer tutorial.
