### ISSUE TITLE
Bolts in Realtime Event Processing tutorial fail to connect to HBase

### ISSUE THREAD

**Issue by TheBellman** [hortonworks/data-tutorials#328]
**Tutorial name**: Realtime Event Processing in Hadoop with NiFi, Kafka and Storm
**Platform version**: HDF 3.0
**Link to tutorial**: https://hortonworks.com/tutorial/realtime-event-processing-in-hadoop-with-nifi-kafka-and-storm/section/5/

### Description of issue:
In the last part of this tutorial, all the HBase bolts fail in the same way using the Sandbox VM, and no data is ever placed into HBase:
`java.lang.RuntimeException: HBase bolt preparation failed: java.lang.reflect.InvocationTargetException at org.apache.storm.hbase.common.HBaseClient.<init>(HBaseClient.java:51) at org.apache.storm.hb`

Additionally, the various ports that would allow delving deeper into the state of Storm and the bolts are not open on the sandbox, making it very difficult to gather much more information.

### Proposed fix (if any):
Revise the setup of the tutorial after testing against the HDF 3.0 sandbox, and ensure ports are opened.

**Comment by dwelden** [comment]
Same exact issue occurring on HDP sandbox with all required services running
`Sandbox information:
Created on: 28_07_2017_14_21_49 for
Hadoop stack version:  Hadoop 2.7.3.2.6.1.0-129
Ambari Version: 2.5.1.0-159
Ambari Hash: 7a4fc4d6ab88f423fb6e6d960c26a961572d0507
Ambari build:  Release : 159
Java version:  1.8.0_141
OS Version:  CentOS release 6.9 (Final)`

**Comment by james94** [comment]
@TheBellman @dwelden 

Hello guys, this tutorial "realtime event processing in hadoop with NiFi, Kafka and Storm" will be redirected to "https://hortonworks.com/tutorial/real-time-event-processing-in-nifi-sam-schema-registry-and-superset/". The tutorial provided in the link uses a newer version of the Trucking IoT reference application. Please refer to this newer tutorial.
