### ISSUE TITLE
Hyperlink "Learning the Ropes of the Hortonworks " not working

### ISSUE THREAD

**Issue by samratsinha** [hortonworks/data-tutorials#331]
**Tutorial name**: <>LOADING SENSOR DATA INTO HDFS
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**: <Either a Hortonworks link or GitHub link works fine>

**Comment by gdeleon5** [comment]
Thanks for reporting - issue resolved!
