### ISSUE TITLE
The tutorial page, https://hortonworks.com/tutorial/loading-data-into-the-hortonworks-sandbox,  which has the file to upload the Sample error 404

### ISSUE THREAD

**Issue by Mjc777** [hortonworks/data-tutorials#346]
**Tutorial name**: <Add tutorial name here>
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**: <Either a Hortonworks link or GitHub link works fine>

**Comment by gdeleon5** [comment]
Thanks for reporting - issue resolved!
