### ISSUE TITLE
Broken Link Zeppelin UI 

### ISSUE THREAD

**Issue by Mjc777** [hortonworks/data-tutorials#347]
**Tutorial name**: <Add tutorial name here>
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**: <Either a Hortonworks link or GitHub link works fine>

**Comment by gdeleon5** [comment]
Zeppelin UI works correctly:

Ambari -> Zeppelin Notebook -> Summary -> Quick Links -> Zeppelin UI (http://sandbox.hortonworks.com:9995/)

If you're still having an issue, please re-open and explain the process you follow to recreate the issue.

Thank you for reporting issues.
