### ISSUE TITLE
Omniture_logs won't create table? And the queries for the three sample files are broke I get java errors?

### ISSUE THREAD

**Issue by Mjc777** [hortonworks/data-tutorials#348]
**Tutorial name**: <Add tutorial name here>
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**: <Either a Hortonworks link or GitHub link works fine>

**Comment by gdeleon5** [comment]
@Mjc777 Can you please provide additional information:
1. Tutorial name or link
2. Detailed description of issue with logs and errors
3. sandbox-version
4. VM used (VirtualBox, VMWare, Docker)

**Comment by gdeleon5** [comment]
Closed (information needed). Please re-open if problem continues.
