### ISSUE TITLE
https://hortonworks.com/tutorial/using-commandline-manage-files-hdfs/

### ISSUE THREAD

**Issue by dhananjaymehta** [hortonworks/data-tutorials#356]
**Tutorial name**: <HADOOP TUTORIAL – GETTING STARTED WITH HDP>
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**: <https://hortonworks.com/tutorial/hadoop-tutorial-getting-started-with-hdp/section/2/>

### Description of issue:
Under LOADING SENSOR DATA INTO HDFS section links under further reading inFurther readings for -  Manage Files on HDFS with Command Line: Hands-on Tutorial (https://hortonworks.com/tutorial/using-commandline-manage-files-hdfs/)

**Comment by gdeleon5** [comment]
Issue resolved - thank you for reporting.
