### ISSUE TITLE
java exception when using ACID transactions

### ISSUE THREAD

**Issue by OrozcoJonathan** [hortonworks/data-tutorials#358]
**Tutorial name**: <Using Hive ACID Transactions to Insert, Update and Delete Data>
**Platform version**: <HDP 2.6>
**Link to tutorial**: <https://hortonworks.com/tutorial/using-hive-acid-transactions-to-insert-update-and-delete-data/>

### Description of issue:
When doing part 8 of the the hello world tutorial when executing the first query after creating the table i get a java exception. I tried turning ACID transaction on and off again but it did not fix it. Any help on figuring out this exception would be greatly appreciated.

![exception](https://user-images.githubusercontent.com/12588266/27979908-583a58e0-632e-11e7-9e76-ad4151e729f6.PNG)

**Comment by gdeleon5** [comment]
Which DDL/DML statement caused the error?
Was it the first INSERT statement in [section 2](https://hortonworks.com/tutorial/using-hive-acid-transactions-to-insert-update-and-delete-data/#hello-acid)?

Looking at the error message, you should circumvent this error by issuing "set hive.enforce.bucketing=true" before the statement.

Let me know if that works for you?

Btw. Which virtual machine are you running (Docker, VirtualBox, or VMWare)?
Also, please provide sandbox version by issuing command in shell-in-the-box: "**sandbox-version**".

**Comment by gdeleon5** [comment]
Thank you for reporting - Issue resolved.
