### ISSUE TITLE
Minor typos in java Spark tutorial (Scala artifacts)

### ISSUE THREAD

**Issue by vadim-volkov** [hortonworks/data-tutorials#365]
**Tutorial name**: Setting up a Spark Development Environment with Java
**Platform version**: HDP 2.6
**Link to tutorial**:  [https://hortonworks.com/tutorial/setting-up-a-spark-development-environment-with-java/](url)

//tutorial-802

### Description of issue:
Minor typos in Spark java tutorial (artifacts from original Scala tutorial)
src/main/scala
Main.scala
### Proposed fix (if any):
src/main/scala -> src/main/java
Main.scala -> Main.java

**Comment by gdeleon5** [comment]
Tutorial has been updated. Thank you for reporting issue.
