### ISSUE TITLE
Hadoop tutorial, syntax error?

### ISSUE THREAD

**Issue by karinmaatman** [hortonworks/data-tutorials#371]
**Tutorial name**: Hadoop Tutorial – Getting Started with HDP
**Platform version**: hdp-2.6.0
**Link to tutorial**: https://hortonworks.com/tutorial/hadoop-tutorial-getting-started-with-hdp/section/4/

### Description of issue: In the Pig Risk Factor tutorial ("Calculate the total non normal events for each driver" paragraph), the code given to "Foreach statement to add the occurance": 
e = foreach d generate group as driverid, SUM(c.occurance) as t_occ; 
produces the following syntax error:
2017-08-08 14:11:30,999 [main] ERROR org.apache.pig.tools.grunt.Grunt - ERROR 1025: 
<file script.pig, line 5, column 23> Invalid field projection. Projected field [GROUP] does not exist in schema: group:chararray,c:bag{:tuple(driverid:chararray,event:chararray,occurance:int)}.

### Proposed fix (if any):
Replacing existing code by: 
e = FOREACH d GENERATE FLATTEN(group) AS driverid, SUM(c.occurance) AS t_occ;

**Comment by gdeleon5** [comment]
Unfortunately, I was unable to recreate your issue.

Can you please provide "sandbox-version" information?
1. Use SSH client or built-in web client (http://sandbox.hortonworks.com:4200/)
2. logon using userid: root, password: hadoop
3. type: "sandbox-version"

I successfully ran tutorial using:
Sandbox information:                                                                                                                                                  
Created on: 28_07_2017_14_21_49 for                                                                                                                                   
Hadoop stack version:  Hadoop 2.7.3.2.6.1.0-129                                                                                                                       
Ambari Version: 2.5.1.0-159                                                                                                                                           
Ambari Hash: 7a4fc4d6ab88f423fb6e6d960c26a961572d0507                                                                                                                 
Ambari build:  Release : 159                                                                                                                                          
Java version:  1.8.0_141                                                                                                                                              
OS Version:  CentOS release 6.9 (Final)

**Comment by gdeleon5** [comment]
@karinmaatman, also let me know how you deployed the sandbox (VirtualBox, VMWare, or native Docker)?

**Comment by karinmaatman** [comment]
Sandbox information:                                                                                                                                                                                               
Created on: 05_05_2017_13_16_20 for                                                                                                                                                                                
Hadoop stack version:  Hadoop 2.7.3.2.6.0.3-8                                                                                                                                                                      
Ambari Version: 2.5.0.5-1                                                                                                                                                                                          
Ambari Hash: 0b5e975972e7a0b265e87b2e38eefde9039ef44c                                                                                                                                                              
Ambari build:  Release : 1                                                                                                                                                                                         
Java version:  1.8.0_131                                                                                                                                                                                           
OS Version:  CentOS release 6.9 (Final)                         

And I deployed sandbox in Docker

**Comment by karinmaatman** [comment]
Sorry, accidently I closed this issue

**Comment by gdeleon5** [comment]
@karinmaatman, sorry, again I'm unable to reproduce your error.

I down-leveled to use reported version of the sandbox (05_05_2017_13_16_20) and ran successfully on both VirtualBox and Docker.

Although it should not matter - I'm running using macOS. Which operating system are you using?

You're the first (and only) person to report this issue. I suggest downloading the most recent HDP 2.6.1 sandbox and try again.

Please let me know if issue persists.

**Comment by karinmaatman** [comment]
I use windows. 

No worries about the issue, I managed to work around it, which provided me with some extra experience above and beyond the tutorial.

Thanks for everything.
