### ISSUE TITLE
tab delimited data

### ISSUE THREAD

**Issue by guptavv** [hortonworks/data-tutorials#376]
**Tutorial name**: <loading-and-querying-data-with-hadoop>
**Platform version**: <HDP 2.6.>
**Link to tutorial**: <https://hortonworks.com/tutorial/loading-and-querying-data-with-hadoop/>

### Description of issue: my data do not load properly unless i use '\t'
tab delimited queries in 3.2) 
FIELDS TERMINATED BY 't'

### Proposed fix (if any):
should be FIELDS TERMINATED BY '\t'

**Comment by gdeleon5** [comment]
Issue resolved - thank you for reporting.
