### ISSUE TITLE
Wrong values loaded from tsv files

### ISSUE THREAD

**Issue by ThomasCollignon** [hortonworks/data-tutorials#377]
**Tutorial name**: LOADING AND QUERYING DATA WITH HADOOP
**Platform version**: HDP 2.6
**Link to tutorial**: https://hortonworks.com/tutorial/loading-and-querying-data-with-hadoop/#load-data-into-tables

### Description of issue:
After executing the requests LOAD DATA ... from retail files, the values are not correctly filled. For example the request "select * from products limit 100;" show a table with every url value being "h" and every category value being "".

**Comment by gdeleon5** [comment]
Issue resolved - thank you for reporting.
