### ISSUE TITLE
Enter the  Ambari Welcome URL         is afu

### ISSUE THREAD

**Issue by TPMoyer** [hortonworks/data-tutorials#378]
**Tutorial name**: <Add tutorial name here>
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**: <Either a Hortonworks link or GitHub link works fine>
https://hortonworks.com/tutorial/learning-the-ropes-of-the-hortonworks-sandbox/#setup-ambari-admin-password-azure
 
### Description of issue:   
  Two Issures:   
      1)   Section 2.3 is unfollowable.     No prior instance of the suggested  "Ambari Welcome URL"  was made.   
    2) an error on the first set of tutorials has not been fixed for well over a year.    Are you trying to drive people to CDH?

### Proposed fix (if any):
Instruct user to     logon to ambari     http://host:8080   as admin
Direct them to the admin pulldown, and suggest they click on the      Manage Ambari 
![image](https://user-images.githubusercontent.com/5302976/30063013-2039a524-921b-11e7-912d-d5ebd4f46d2f.png)

**Comment by gdeleon5** [comment]
Issue resolved - thank you for reporting.
