### ISSUE TITLE
Cross-Component Lineage With Atlas

### ISSUE THREAD

**Issue by patalwell** [hortonworks/data-tutorials#379]
**Tutorial name**: cross-component-lineage-with-apache-atlas-across-apache-sqoop-hive-kafka-storm
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**: https://hortonworks.com/hadoop-tutorial/cross-component-lineage-apache-atlas/
### Description of issue:
This tutorial links to a zip file contained on the hortonwork's repository; however said repository and files no longer exist. See command: wget https://raw.githubusercontent.com/hortonworks/data-tutorials/master/tutorials/hdp/hdp-2.5/cross-component-lineage-with-apache-atlas-across-apache-sqoop-hive-kafka-storm/assets/crosscomponent_scripts.zip

For the tutorial to work one also needs to configure sqoop and storm to work with the atlas webhook.

### Proposed fix (if any):
Place the relevant files back on the repository for tutorial purposes. wget https://github.com/hortonworks/data-tutorials/blob/archive-hdp-2.5/tutorials/hdp/hdp-2.5/cross-component-lineage-with-apache-atlas-across-apache-sqoop-hive-kafka-storm/assets/crosscomponent_scripts.zip?raw=true works in the interim.

Create a section that lets users know they also need to enable the Atlas webhook for sqoop and storm within the tutorial.

**Comment by pietrotull** [comment]
just a reminder, this is still broken

**Comment by james94** [comment]
@patalwell 
@pietrotull 
I am working on updating the tutorial with your suggestions. I am also fixing any problems I run into on the latest HDP 2.6.4 SB. Here is a link to the fork with latest changes:

https://github.com/james94/data-tutorials/blob/master/tutorials/hdp/cross-component-lineage-with-apache-atlas-across-apache-sqoop-hive-kafka-storm/tutorial.md

Please let me know if you have any other issues.

**Comment by patalwell** [comment]
Thanks James!

Pat Alwell
San Diego, CA
540-226-7365
--------------------------------
Solutions Engineer | Hortonworks

**Comment by james94** [comment]
Hey @patalwell and @pietrotull ,

I fixed the tutorial issues. I was able to get through the tutorial and provided extra steps that were needed. Please give it a try and provide any necessary feedback.

**Comment by patalwell** [comment]
Thanks James, I'll close this for now.
