### ISSUE TITLE
Query RDD using Spark SQL

### ISSUE THREAD

**Issue by mouldyjon** [hortonworks/data-tutorials#380]
**Tutorial name**: Hive with ORC in Spark REPL
**Platform version**: HDP 2.6
**Link to tutorial**: https://github.com/hortonworks/data-tutorials/blob/master/tutorials/hdp/using-hive-with-orc-from-apache-spark/tutorial.md

### Description of issue:

The tutorial has you run a Spark SQL commands to query an RDD.

`val results = sqlContext.sql("SELECT * FROM yahoo_stocks_temp")`

See link https://github.com/hortonworks/data-tutorials/blob/master/tutorials/hdp/using-hive-with-orc-from-apache-spark/tutorial.md#querying-against-the-table

However this command returns the following error:

`<console>:32: error: not found: value sqlContext
       val results = sqlContext.sql("SELECT * FROM yahoo_stocks_temp")`

### Proposed fix (if any):
The command should be changed to:
`val results = spark.sqlContext.sql("SELECT * FROM yahoo_stocks_temp")`

**Comment by gdeleon5** [comment]
@roberthryniewicz can you please take a look at this issue. [Tutorial](https://hortonworks.com/tutorial/using-hive-with-orc-from-apache-spark/) seems to be out of date regarding Spark 2.2.0 and using deprecated APIs.

**Comment by roberthryniewicz** [comment]
Resolved.
