### ISSUE TITLE
wrong sandbox port:8888

### ISSUE THREAD

**Issue by wbwangk** [hortonworks/data-tutorials#382]
**Tutorial name**: <Add tutorial name here>
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**: <Either a Hortonworks link or GitHub link works fine>

### Description of issue:
Ambari address in sandbox is 127.0.0.1:8080.  "127.0.0.1:8888" is wrong.

**Comment by gdeleon5** [comment]
@wbwangk, in which tutorial do you see port 8888 being used?

**Comment by gdeleon5** [comment]
Agreed, port 8888 references the sandbox splash page, not Ambari.

Closing issue.
Please re-open when you can provide reference to tutorial that references port 8888 for Ambari.
