### ISSUE TITLE
documentation improvement

### ISSUE THREAD

**Issue by naveenoxford** [hortonworks/data-tutorials#383]
**Tutorial name**: hadoop-tutorial-getting-started-with-hdp/section/5/
**Platform version**: HDP 2.6
**Link to tutorial**: https://hortonworks.com/tutorial/hadoop-tutorial-getting-started-with-hdp/section/5/
### Description of issue:
this is a documentation issue/improvement. There is a sentence "For improved Hive integration, ORC file support for Spark." I think that sentence can be improved.

### Proposed fix (if any):
change documentation

**Comment by gdeleon5** [comment]
Tutorial has been updated. Thank you for reporting issue.
