### ISSUE TITLE
typo issue in documetation

### ISSUE THREAD

**Issue by naveenoxford** [hortonworks/data-tutorials#384]
**Tutorial name**: REAL-TIME EVENT PROCESSING IN NIFI, SAM, SCHEMA REGISTRY AND SUPERSET
**Platform version**: HDF 3.0
**Link to tutorial**: 
https://hortonworks.com/tutorial/real-time-event-processing-in-nifi-sam-schema-registry-and-superset/
### Description of issue:
identified typo - "Druid provides data ingestion is in real-time with low latency, flexible data exploration and quick aggregation."

### Proposed fix (if any):
"Druid provides data ingestion in real-time with low latency, flexible data exploration and quick aggregation."

**Comment by afinnell** [comment]
Is it possible to reword it in such a way it doesn't cause the term "real-time" to be overloaded? Perhaps "Druid provides low-latency live data ingestion, flexible data exploration and aggregation." 

Just my two cents. If it's going to be touched I thought there may be an opportunity here to not use the term "real-time."

**Comment by gdeleon5** [comment]
Issue resolved. Thanks for reporting issue.
