### ISSUE TITLE
Link to scripts used to create the roles is missing

### ISSUE THREAD

**Issue by edennuriel** [hortonworks/data-tutorials#385]
**Tutorial name**: LEARNING THE ROPES OF THE HORTONWORKS SANDBOX
**Platform version**: HDP 2.6.1
**Link to tutorial**: https://hortonworks.com/hadoop-tutorial/learning-the-ropes-of-the-hortonworks-sandbox/

### Description of issue:
broken link - script for creating the roles is not found on github (https://raw.githubusercontent.com/hortonworks/data-tutorials/cf9f67737c3f1677b595673fc685670b44d9890f/tutorials/hdp/hdp-2.5/learning-the-ropes-of-the-hortonworks-sandbox/assets/User_Scripts)

### Proposed fix (if any):
update the link to a valid location

**Comment by gdeleon5** [comment]
The tutorial has been significantly updated. I believe this issue has been resolved. If not, please re-open.

Thank you for reporting issue.
