### ISSUE TITLE
Starting HDP 2.6.1 from docker image is failing with /usr/bin/docker-current: Error response from daemon: driver failed programming external connectivity on endpoint sandbox-hdp 

### ISSUE THREAD

**Issue by mdhanji** [hortonworks/data-tutorials#388]
**Tutorial name**: <Installing HDP 2.6.1 docker image>
**Platform version**: <HDP 2.6 Docker image on Redhat Linux 7.4
**Link to tutorial**: <https://hortonworks.com/tutorial/sandbox-deployment-and-install-guide/section/3/>

### Description of issue:
I am having issue starting the HDP 2.6.1 Docker Image.
I have followed the instructions as per link https://hortonworks.com/tutorial/sandbox-deployment-and-install-guide/section/3/.

Here is the output of the commands executed on the Linux OS:

[hdp]$ sudo docker load < software/HDP_2_6_1_docker_image_28_07_2017_14_42_40.tar
b1b065555b8a: Loading layer [==================================================>] 202.2 MB/202.2 MB
894c5a8d24dd: Loading layer [==================================================>] 12.11 GB/12.11 GB
Loaded image: sandbox-hdp:latest

[hdp]$ sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
sandbox-hdp         latest              c3cef4760133        8 weeks ago         12.2 GB

[hdp]$ sudo ./start_sandbox-hdp.sh
Waiting for docker daemon to start up:
ed21952124fd152b433aa170eb4446015c8687b1f20ad24378bebf49d96a8e5a
/usr/bin/docker-current: Error response from daemon: driver failed programming external connectivity on endpoint sandbox-hdp (88777963eec3ebe22f0c0eb07878ce64a09b6e6a925e65ce62338e82aeea2e78): exec: "docker-proxy": executable file not found in $PATH.
Error response from daemon: Container ed21952124fd152b433aa170eb4446015c8687b1f20ad24378bebf49d96a8e5a is not running
Error response from daemon: Container ed21952124fd152b433aa170eb4446015c8687b1f20ad24378bebf49d96a8e5a is not running
Error response from daemon: Container ed21952124fd152b433aa170eb4446015c8687b1f20ad24378bebf49d96a8e5a is not running
Error response from daemon: Container ed21952124fd152b433aa170eb4446015c8687b1f20ad24378bebf49d96a8e5a is not running
Error response from daemon: Container ed21952124fd152b433aa170eb4446015c8687b1f20ad24378bebf49d96a8e5a is not running
Error response from daemon: Container ed21952124fd152b433aa170eb4446015c8687b1f20ad24378bebf49d96a8e5a is not running
Error response from daemon: Container ed21952124fd152b433aa170eb4446015c8687b1f20ad24378bebf49d96a8e5a is not running
Waiting for ambari agent to connect

Can you please assist....

**Comment by mdhanji** [comment]
Edgar - is this something you can assist with please?

**Comment by gdeleon5** [comment]
[HDP 2.6.3 sandbox](https://hortonworks.com/downloads/#sandbox) is now available and scripts have been updated. The reported issue should be fixed now.

Thank you for reporting issue.
