### ISSUE TITLE
Add Tutorial: Fine Grained Permissions for HDFS files in Hadoop using HDFS ACL`s

### ISSUE THREAD

**Issue by ZacBlanco** [hortonworks/data-tutorials#39]
Please Fill in the Following Information before submitting your Issue:

**Tutorial Name**: Fine Grained Permissions for HDFS files in Hadoop using HDFS ACL`s
**HDP Version are you Running**: 2.4
**Applicable HDP Components**: HDFS

**Link to tutorial**(Hortonworks or GitHub website):http://hortonworks.com/hadoop-tutorial/fine-grained-permissions-hdfs-files-hadoop-using-hdfs-acls/
### Detailed Description of Issue:

Tutorial needs to be imported and updated for HDP 2.4
### Proposed Fix:

Work with 2.4 sandbox to update images and text appropriately

**Comment by orendain** [comment]
A bit delayed, but verified that the tutorial was updated and compatible with most recent HDP release (2.5).
