### ISSUE TITLE
Tutorial Fails to Create Table truck_mileage From Existing Trucking Data

### ISSUE THREAD

**Issue by tjmitch** [hortonworks/data-tutorials#395]
**Tutorial name**: Hadoop Tutorial – Getting Started with HDP - Hive Data ETL 
**Platform version**:  HDP 2.6
**Link to tutorial**: https://hortonworks.com/tutorial/hadoop-tutorial-getting-started-with-hdp/section/3/

### Description of issue: Script provided in the Hive Data ETL tutorial to create the truck_mileage table fails with "out of memory" error.  Workaround described in the Hortonworks Community Connection does not work.  (https://community.hortonworks.com/questions/12067/what-is-the-workaround-when-getting-hive-outofmemo.html)  This workaround requires changing specific configuration parameters; however, changing them results in warnings regarding other parameters and the script still blows up.  

Because this table is not created, all subsequent scripts in following tutorials that  depend on that table also fail.  This defeats the purpose of the tutorials. 

See the attached file for the error listing.
[171011 Hortonworks Tutorial Fail - Hive Data ETL - out of memory.docx](https://github.com/hortonworks/data-tutorials/files/1376190/171011.Hortonworks.Tutorial.Fail.-.Hive.Data.ETL.-.out.of.memory.docx)

**Comment by gdeleon5** [comment]
@tjmitch, Thank you for reporting the issue.
I personally have not encountered this problem. Let's begin with the basics and see if we can resolve your issue:

1. Which Operating System are you using?
2. Which VM are you using (i.e native Docker, VirtualBox, VMWare)?
3. Which sandbox version are you using? You can get this by using shell-in-a-box ```http://localhost:4200``` or ```ssh -p 2222 root@localhost```. In the command-line, type **sandbox-version**
4. Make sure you've allocated at least 8GB to the VM. See [Sandbox Deployment Guide](https://hortonworks.com/tutorial/sandbox-deployment-and-install-guide/)

**Comment by tjmitch** [comment]
Hello, gdeleon5 - Thank you for getting back to me on this.  Answers to your questions follow:


System Info:

Windows 10 Home 64-bit
16.0 GB RAM*
Intel Core i3-4170 CPU @3.70 GHz
VM:
Oracle VM VirtualBox 5.1.28 r117968 (Qt5.6.2)
Sandbox:
Created on:  25_10_2016_08_11_26 for
Hadoop stack version:  Hadoop 2.7.3.2.5.0.0-1245
Ambari Version:  2.4.0.0-1225
Ambari Hash:  59175b7aa1ddb74b85551c632e3ce42fed8f0c85
Ambari build:  Release: 1225
Java version:  1.8.0_111
OS Version:  CentOS release 6.8 (Final)

HDP 2.5
Memory:  8192 MB Base Memory (Settings/System/Motherboard Base Memory)
*I installed an additional 8GB base memory specifically to dedicate that to use by the virtual machine.

Please let me know if there is any other information you require at this time.  Thank you for looking into this...tm


Terry Mitchell


________________________________

**Comment by gdeleon5** [comment]
@tjmitch , thanks for the info.

I see you're using an old sandbox. You may consider updating to the most current, which I know many issues have been resolved - [current sandbox](https://hortonworks.com/downloads/#sandbox)

**Comment by tjmitch** [comment]
Interesting, I only installed the version of the sandbox in February.  I will look into updating the sandbox.  Thanks for the info…tm

**Comment by tjmitch** [comment]
gdeleon5:  I deleted the 2.5 version and downloaded and installed 2.6.  It ran fine the first time I tried, and I was able to create the needed file in the tutorial that led to my issuing the first error report.

However, since that first session, I have tried several times to run the new 2.6 Sandbox, but it gets hung up in the startup process.  It reaches the point where it says “Started Cleanup of Temporary Directories” and then hangs; I left it run overnight and it never gets past that point.  The process is picking up time, so it’s doing something, but never finishes.  Why it worked the first time I do not know.  I removed and reinstalled the new Sandbox but it still hangs.  Should I issue another error report?

Thank you for you help…T. Mitchell

**Comment by tjmitch** [comment]
Update:  after updating the VirtualBox itself the Sandbox startup time is now about 8 minutes.  I don’t think the update to VirtualBox has anything to do with the improved startup time, but I don’t know that it doesn’t.  Could be coincidence, I can’t say.  Regardless, 8 minutes is better than 8 hours – or infinity.  Startup time for Sandbox 2.5 was a couple minutes, I never timed it because it wasn’t that much of a bother.  8 minutes seems unduly long, but at lease it doesn’t hang anymore.

I will not write another trouble report unless I have a repeat of the hung startup process.  Thanks again for your help…tm

From: Terry Mitchell
Sent: Friday, October 20, 2017 7:10 AM
To: hortonworks/data-tutorials <reply@reply.github.com>
Subject: RE: [hortonworks/data-tutorials] Tutorial Fails to Create Table truck_mileage From Existing Trucking Data (#395)

gdeleon5:  I deleted the 2.5 version and downloaded and installed 2.6.  It ran fine the first time I tried, and I was able to create the needed file in the tutorial that led to my issuing the first error report.

However, since that first session, I have tried several times to run the new 2.6 Sandbox, but it gets hung up in the startup process.  It reaches the point where it says “Started Cleanup of Temporary Directories” and then hangs; I left it run overnight and it never gets past that point.  The process is picking up time, so it’s doing something, but never finishes.  Why it worked the first time I do not know.  I removed and reinstalled the new Sandbox but it still hangs.  Should I issue another error report?

Thank you for you help…T. Mitchell

**Comment by gdeleon5** [comment]
@tjmitch : Thanks for upgrading to the latest (HDP 2.6.1)

Sorry to hear you had issues with the latest sandbox:
- first time deployment was successful
- subsequent deployments fail.

I am also glad that upgrading VirtualBox resolved the subsequent deployment delays/failure. I also believe this is coincidental.

I will close this issue. If you continue having issues, please create new issue.
