### ISSUE TITLE
Tutorial syntax for FIELDS TERMINATED BY doesn't work.

### ISSUE THREAD

**Issue by mihamerstan** [hortonworks/data-tutorials#396]
**Tutorial name**: tutorial-230
**Platform version**:hdp-2.6.0
**Link to tutorial**: <Either a Hortonworks link or GitHub link works fine>

### Description of issue:
In section 3.2, the tutorial creates 3 tables with a SQL query:
CREATE TABLE...
FIELDS TERMINATED BY 't'
...

This second line should read FIELDS TERMINATED BY '\t' , for the tab separated file format of the example.  Note: This might be due to different syntax in 2.6.1?  I'm not sure.
  
### Proposed fix (if any):
Changing the text in the tutorial.

**Comment by gdeleon5** [comment]
Tutorial in reference is [LOADING AND QUERYING DATA WITH HADOOP](https://hortonworks.com/tutorial/loading-and-querying-data-with-hadoop/#create-hive-tables)

**Comment by gdeleon5** [comment]
Issue resolved - thank you for reporting.

**Comment by mihamerstan** [comment]
Great, thanks!
