### ISSUE TITLE
start_sandbox-hdp.sh won't work if you reset Ambari admin password

### ISSUE THREAD

**Issue by jkolter** [hortonworks/data-tutorials#397]
**Tutorial name**: Learning the Ropes of the Hortonworks Sandbox/Install Sandbox on Docker
**Platform version**: HDP 2.6
**Link to tutorial**: https://hortonworks.com/tutorial/learning-the-ropes-of-the-hortonworks-sandbox
https://hortonworks.com/tutorial/sandbox-deployment-and-install-guide/section/3/

### Description of issue:

When installing the Sandbox using Docker (at least Docker, maybe others) we are given a link to download the latest "start_sandbox-hdp.sh" script.  The latest version @2150317 has changed the commands to start the sandbox to use the REST version and hard coded the admin password.  If a user changes the admin password in Ambari the container will fail to start with no error message until a timeout.  The "learning the ropes" tutorial directs users to change the admin password in section 2.2
 
### Proposed fix (if any):

Assuming you won't change the script to not hard code an admin password, the documentation needs to include the password for the admin user, and/or instructions that detail how you need to change the password by not only using the ambari-admin-password-reset command but to also then change the startup script to match the new credentials.

**Comment by gdeleon5** [comment]
The startup script has been updated so that changing admin password will not affect the sandbox startup.

Thanks for reporting issues.
