### ISSUE TITLE
Wrong Hive query

### ISSUE THREAD

**Issue by Hiyorimi** [hortonworks/data-tutorials#398]
**Tutorial name**: Hive - Data ETL
**Platform version**: HDP 2.6, HDF 2.2, etc.
**Link to tutorial**: https://hortonworks.com/tutorial/hadoop-tutorial-getting-started-with-hdp/section/3/

### Description of issue:
Syntax of a command for creating truck_mileage should be: 
```
CREATE TABLE truck
_mileage STORED AS ORC AS
  SELECT truckid, driverid, rdate, miles, gas, miles / gas as mpg
```

### Proposed fix (if any):

put "as" into the command

**Comment by gdeleon5** [comment]
Functionality, the following statements are equivilent:
"miles / gas **as** mpg" vs. "miles / gas mpg"
