### ISSUE TITLE
File /tmp/.pigjobs/riskfactorpig_01-11-2017-15-18-50/stderr not found

### ISSUE THREAD

**Issue by tjmitch** [hortonworks/data-tutorials#401]
**Tutorial name**: Hadoop Tutorial – Getting Started with HDP
HCC Tags: tutorial-100 and hdp-2.6.0
**Platform version**: HDP 2.6.0
**Link to tutorial**: https://hortonworks.com/tutorial/hadoop-tutorial-getting-started-with-hdp/section/4/#execute-pig-script-on-tez

### Description of issue:  Job starts but does not complete.  Table "riskfactor" created and headings inserted, but no data.  Log contains the single line:

File /tmp/.pigjobs/riskfactorpig_01-11-2017-15-18-50/stderr not found

### Proposed fix (if any):  Unknown.  Looks like a missing temp file.

**Comment by gdeleon5** [comment]
Sorry, I was unable to recreate this issue using HDP 2.6.1.
We've recently made [HDP 2.6.3](https://hortonworks.com/downloads/#sandbox) available. Please try again and if the issue still persists, please reopen.

Thank you for reporting issue.
