### ISSUE TITLE
Spark2 error with tutorial

### ISSUE THREAD

**Issue by orendain** [hortonworks/data-tutorials#404]
**Tutorial name**: Hands-On Tour of Apache Spark in 5 Minutes
**Platform version**: HDP 2.6.1 (probably)
**Link to tutorial**: https://github.com/hortonworks/data-tutorials/blob/7cfcc7d6090568945698daa6bdd818116e33372e/tutorials/hdp/hands-on-tour-of-apache-spark-in-5-minutes/tutorial.md

### Description of issue:
Steven Tam and Dave Welden reported this issue and a possible resolution here:
https://community.hortonworks.com/questions/140279/wrt-your-tutorial-after-creating-spark2-following.html

**Comment by gdeleon5** [comment]
Hive should already been started automatically when sandbox is deployed. If not, there should be "red" markings on Ambari dashboard as a hint that something is not running properly.

HCC is a great place to find answers to these type of problems (not tutorials).
