### ISSUE TITLE
NiFi port is not forwarded in HDF startup script

### ISSUE THREAD

**Issue by waveaccess** [hortonworks/data-tutorials#409]
**Tutorial name**: Deploying Hortonworks Sandbox on Docker
**Platform version**: HDF 2.2
**Link to tutorial**: https://hortonworks.com/tutorial/sandbox-deployment-and-install-guide/section/3/#start-sandbox

### Description of issue:
Apache NiFi UI is not accessible because port forwarding rule for port 19090 is missed in startup script. Issue is in both Shell and PowerShell scripts.

### Proposed fix (if any):
Add missing rule to the list

**Comment by gdeleon5** [comment]
NiFi UI uses port 9090 in the sandbox. The startup scripts does have this port opened.

Thank you for reporting issues.
