### ISSUE TITLE
Add Tutorial: Secure JDBC and ODBC Connection to Hive with Knox

### ISSUE THREAD

**Issue by ZacBlanco** [hortonworks/data-tutorials#41]
Please Fill in the Following Information before submitting your Issue:

**Tutorial Name**: Secure JDBC and ODBC Clients’ Access to HiveServer2 using Apache Knox
**HDP Version are you Running**: 2.4.0
**Applicable HDP Components**: Knox, Hive

**Link to tutorial**(Hortonworks or GitHub website):http://hortonworks.com/hadoop-tutorial/secure-jdbc-odbc-clients-access-hiveserver2-using-apache-knox/
### Detailed Description of Issue:

Tutorial needs to be updated to be compatible with HDP 2.4
### Proposed Fix:

Update text and images so that the tutorial works with 2.4

**Comment by orendain** [comment]
A bit delayed, but verified that the tutorial was updated and compatible with most recent HDP release (2.5).
