### ISSUE TITLE
SSH login issue on port 2222

### ISSUE THREAD

**Issue by daudkamal** [hortonworks/data-tutorials#411]
**Tutorial name**: Learning the Ropes of the Hortonworks Sandbox
**Platform version**: HDP 2.6
**Link to tutorial**: https://hortonworks.com/tutorial/learning-the-ropes-of-the-hortonworks-sandbox/
### Description of issue:
I am following this tutorial to learn the ropes of the hortonworks sandbox while doing so I ran into an issue regarding the SSH Login using shell web client. The default username and password root / hadoop don't seem to work. I haven't change the passwords for Hortonworks when I 1st used it. They still work for the virtual machine root login.
### Proposed fix (if any):
I tried to log into SSH manually on the virtual machine using the port 2222 but it didn't work. but when I tried the same using port 22 it logged me in. However, most of the tutorials are done using the shell web client which I am unable to use.

**Comment by gdeleon5** [comment]
The very first time you logon the sandbox, using either web client or ssh from terminal, you are **required** to change the password.

```
$ssh -p 2222 root@sandbox-hdp.hortonworks.com
root@sandbox-hdp.hortonworks.com's password:
You are required to change your password immediately (root enforced)
Changing password for root.
(current) UNIX password:
New password:
Retype new password:
```

I suggest removing your current Sandbox VM and re-deploying it: [sandbox](https://hortonworks.com/downloads/#sandbox) . Make sure MD5 hash value matches.

If you're still having issues, please let me know.

**Comment by gdeleon5** [comment]
@daudkamal Closing issue due to no response.

I suggest downloading the [latest HDP 2.6.4 sandbox](https://hortonworks.com/downloads/#sandbox ) and try again. If you're still having issues, please re-open issue:
