### ISSUE TITLE
IOT HDF Tutorial - Extract Process issue with Timestamp RegEx

### ISSUE THREAD

**Issue by jimnin73** [hortonworks/data-tutorials#414]
**Tutorial name**: Analyze IoT Weather Station Data via Connected Data Architecture
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**:  https://hortonworks.com/tutorial/analyze-iot-weather-station-data-via-connected-data-architecture/

### Description of issue:
Timestamp was not being extracted in NiFi flow

### Proposed fix (if any):
Change RegEx for Timestamp in ExtractText Processor to (?<=Time = )(\w+-\w+-\w+:\w+:\w+)

**Comment by jimnin73** [comment]
Here is an example of the raw content...

Serial = 00000000609a3ed0
Time = 2017-12-12T04:43:12Z
Temperature_F = 52.22
Humidity_PRH = 26.16
Pressure_In = 0.0
Public_IP = 73.211.3.29

**Comment by jimnin73** [comment]
Here is an example of the data payload from the WeatherStation.py script:

Serial = 00000000609a3ed0
Time = 2017-12-12T05:03:30Z
Temperature_F = 67.49
Humidity_PRH = 19.45
Pressure_In = 28.74
Public_IP = 73.211.3.29

**Comment by james94** [comment]
Thank you for the feedback @jimnin73 
I will be working on getting this change updated in the tutorial.

**Comment by james94** [comment]
I updated the tutorial. I will double check your suggestion for the ExtractText Processor @jimnin73

**Comment by james94** [comment]
@jimnin73 this issue is addressed in the latest version of the tutorial series, which will be updated on the website very soon.
