### ISSUE TITLE
Change the path to hosts file

### ISSUE THREAD

**Issue by stonefl** [hortonworks/data-tutorials#416]
**Tutorial name**: <Learning the Ropes of the Hortonworks Sandbox>
**HCC Tag**: <tutorial-160 >
**Platform version**: <hdp-2.6.0>
**Link to tutorial**: <https://hortonworks.com/tutorial/learning-the-ropes-of-the-hortonworks-sandbox/#map-sandbox-ip-to-your-desired-hostname-in-the-hosts-file>

### Proposed fix (if any): change path from `c:WindowsSystem32driversetchosts` to
`C:\Windows\System32\drivers\etc\hosts`.

**Comment by Castro38** [comment]
The tutorial has been updated. Thank you for reporting the issue.
