### ISSUE TITLE
HDP 2.6 Sandbox Docker container does not start on the Docker for Mac 17.12.0-ce-mac46 (21698)

### ISSUE THREAD

**Issue by yohei1126** [hortonworks/data-tutorials#423]
**Tutorial name**: SANDBOX DEPLOYMENT AND INSTALL GUIDE
**Platform version**: HDP 2.6
**Link to tutorial**: https://jp.hortonworks.com/tutorial/sandbox-deployment-and-install-guide/

### Description of issue:

- I have tired it on Docker for Mac 17.12.0-ce-mac46 (21698). https://store.docker.com/editions/community/docker-ce-desktop-mac
- Run the shell script `start_sandbox-hdp.sh` after loading the docker image for HDP 2.6 Sand box
- It should ends with the message `"Started Hortonworks HDP container"` but it does not end

```
$ ./start_sandbox-hdp.sh 
Waiting for docker daemon to start up:
b1c83479310167c1f3f3186eaac0ae8a7b85f0eb28791cb5f139cc6fa2258655
Using python  /usr/bin/python
Starting ambari-server
Ambari Server running with administrator privileges.
Organizing resource files at /var/lib/ambari-server/resources...
Ambari database consistency check started...
Server PID at: /var/run/ambari-server/ambari-server.pid
Server out at: /var/log/ambari-server/ambari-server.out
Server log at: /var/log/ambari-server/ambari-server.log
Waiting for server start................................
Server started listening on 8080

DB configs consistency check: no errors and warnings were found.
Ambari Server 'start' completed successfully.
```

### Proposed fix (if any):

- The script should successfully end.

**Comment by gdeleon5** [comment]
Thank you for reporting issue. We'll investigate the issue.

**Comment by gdeleon5** [comment]
Using Docker 17.09, no issue was found.
When upgraded to 17.12, the script hangs as described by @yohei1126

**Comment by yohei1126** [comment]
Thanks. I tried it again after deleting all containers and images but still it get stuck in the middle.

```
$ docker --version
Docker version 17.12.0-ce, build c97c6d6
$ ./start_sandbox-hdp.sh 
Waiting for docker daemon to start up:
ac20b43ffafdcbb654d42d33081dd0f76d812808bac2f17a6afc4efa69e3b9b2
Using python  /usr/bin/python
Starting ambari-server
Ambari Server running with administrator privileges.
Running initdb: This may take up to a minute.
About to start PostgreSQL
Organizing resource files at /var/lib/ambari-server/resources...
Ambari database consistency check started...
Server PID at: /var/run/ambari-server/ambari-server.pid
Server out at: /var/log/ambari-server/ambari-server.out
Server log at: /var/log/ambari-server/ambari-server.log
Waiting for server start............................................
Server started listening on 8080

DB configs consistency check: no errors and warnings were found.
Ambari Server 'start' completed successfully.
```

**Comment by gdeleon5** [comment]
Startup script has been updated to work with latest Docker release 17.12.0. [Please update your startup sceipt](https://hortonworks.com/tutorial/sandbox-deployment-and-install-guide/section/3/#for-hdp-sandbox)

Thanks again for reporting issues.
