### ISSUE TITLE
Setting up a Spark Development Environment with Java

### ISSUE THREAD

**Issue by hw-rdobson** [hortonworks/data-tutorials#427]
**Tutorial name**: setting-up-a-spark-development-environment-with-java
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**: https://hortonworks.com/tutorial/setting-up-a-spark-development-environment-with-java/

### Description of issue:
Missing Package definition in java snippet causes confusion when calling deployment script below

/usr/hdp/current/spark2-client/bin/spark-submit --class "Main" --master local ./SparkTutorial-1.0-SNAPSHOT.jar

### Proposed fix (if any):
add package Hortonworks.SparkTutorial

update deployment script to
/usr/hdp/current/spark2-client/bin/spark-submit --class "Hortonworks.SparkTutorial.Main" --master local ./SparkTutorial-1.0-SNAPSHOT.jar

**Comment by gdeleon5** [comment]
@hw-rdobson Thank you for your suggestions - tutorial has been updated.
