### ISSUE TITLE
Import HDP 3.0 to virtual box : error file is corrupted

### ISSUE THREAD

**Issue by gfloranc** [hortonworks/data-tutorials#458]
**Platform version**: HDP 3.0

### Description of issue:
I want to try to import in my VirtualBox 5.1.26 the following sandbox (HDF_3.0.2.0_virtualbox_01_18_2018)
And I got this issue :
Code d'erreur : | VBOX_E_FILE_ERROR (0x80BB0004)
-- | --
Composant : | ApplianceWrap
Interface : | IAppliance {8398f026-4add-4474-5bc3-2f9f2140b23e}

Thanks

**Comment by gdeleon5** [comment]
@gfloranc can you please provide more details about the the steps take to deploy HDF 3.0.2.0 sandbox? Did you follow the [deploy guide](https://hortonworks.com/tutorial/sandbox-deployment-and-install-guide/section/1/#prerequisites) instructions and meet the prerequisites? Which operating system are you using?

**Comment by gdeleon5** [comment]
We've recently updated [HDF to version 3.1](https://hortonworks.com/downloads/#sandbox). Please download and try again - make sure you follow [deploy guide](https://hortonworks.com/tutorial/sandbox-deployment-and-install-guide) instructions .

If you're still getting the error, please re-open this issue.

**Comment by gfloranc** [comment]
Hi,

Thanks for your help. I've downloaded the HDP virtual box distribution once
again and it works.
Now I'm trying to mount a shared folder and it's not really easy compared
to a cloudera distribution (for which it works easily)

**Comment by gdeleon5** [comment]
@gfloranc I'm glad you were able to get it to work.
I'm not familiar with "shared folders" or how they are used. If you could provide detailed information, we may be able to add a feature request.

**Comment by gfloranc** [comment]
@gdeleon5
For future feature request, is it possible to pre install inside a virtual
box distribution the Virtual Box Guest Addition. It's necessary for the
VBox to mount a shared folder with Window.
Thanks to add it to the backlog
.

**Comment by gdeleon5** [comment]
@gfloranc Can you provide web links to describe what "shared folders" are and how to use?

**Comment by gfloranc** [comment]
You can follow this link to install a shared folder :
https://community.hortonworks.com/articles/44601/mount-virtualbox-shared-folder.html

It doesn't work at the moment. Because inside the VBox distribution, we
need to install the VBoxGuestAddition.
https://forums.virtualbox.org/viewtopic.php?t=15868

Hope thoses links can help.
Thanks for all

**Comment by gdeleon5** [comment]
@gfloranc Thank you. I'll add it to our feature list

**Comment by gdeleon5** [comment]
@gfloranc How are you using this feature?
How will you benefit by this feature?
Is it copy files to/from the sandbox?
Is it copy files to/from HDFS?
Is this needed in support of going through a [tutorial](https://hortonworks.com/tutorials/), which one?

Since this feature is not currently supported, are you using **scp** as a work-around?

**Comment by gfloranc** [comment]
Hi,

This features is the easiest way I found to transfer files between Windows
(the host) and CentOs (the guest). It's to copy files to/from the sandbow.
Could you detail your workaround please (scp) ?

Thanks for your help

**Comment by gdeleon5** [comment]
@gfloranc take a look at [Learning the Ropes](https://hortonworks.com/tutorial/learning-the-ropes-of-the-hortonworks-sandbox/#send-data-between-sandbox-and-local-machine) tutorial.

On Windows environment, you'll need "Git Bash", which you get when you install GitHub.

**Comment by gdeleon5** [comment]
@gfloranc you can also use the [shell-in-the-box](https://hortonworks.com/tutorial/learning-the-ropes-of-the-hortonworks-sandbox/#shell-web-client-method) (no need to install anything)

**Comment by gfloranc** [comment]
It's exactly what I did.
But the sudo mount -t vboxsf folder sf_folder didn't work.
It works on Cloudera VBox
