### ISSUE TITLE
Error while attaching the vmdk file (MD5 : a669529e5e52374bc87d3932d24baba3) in VM 9.0

### ISSUE THREAD

**Issue by debanand0687** [hortonworks/data-tutorials#463]
![a1fc1f3f](https://user-images.githubusercontent.com/12751279/36532113-e2de2af0-17e5-11e8-82e7-5451907a67fd.PNG)
**Tutorial name**: <Add tutorial name here>
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**: <Either a Hortonworks link or GitHub link works fine>

**Comment by gdeleon5** [comment]
@debanand0687 the [prerequisites](https://hortonworks.com/tutorial/sandbox-deployment-and-install-guide/section/2/#prerequisites) are VMWare, version 14 or newer. Please update VMWare and try again.

If you are still having issues, please let us know.
