### ISSUE TITLE
8088 tunnel missing

### ISSUE THREAD

**Issue by trp956s** [hortonworks/data-tutorials#469]
**Tutorial name**: SANDBOX DEPLOYMENT AND INSTALL GUIDE
Deploying Hortonworks Sandbox on Microsoft Azure
OR
**Tutorial name**: LEARNING THE ROPES OF THE HORTONWORKS SANDBOX

**Platform version**: 2.4
**Link to tutorial**: https://hortonworks.com/tutorial/learning-the-ropes-of-the-hortonworks-sandbox/#environment-setup
OR
**Link to tutorial**: https://hortonworks.com/tutorial/sandbox-deployment-and-install-guide/section/4/

### Description of issue:
After following the directions on Deploying Hortonworks Sandbox on Microsoft Azure and LEARNING THE ROPES OF THE HORTONWORKS SANDBOX.  The link to the ResourceManager (http://sandbox-hdp.hortonworks.com:8088/) does not work.  Tutorial readers must also add the following tunnel:
8088 -> 127.0.0.1:8088

### Proposed fix (if any):
Add the following line to the port forward paragraph under https://hortonworks.com/tutorial/sandbox-deployment-and-install-guide/section/4/#using-putty:

```
8088 -> 127.0.0.1:8088
```

**Comment by gdeleon5** [comment]
Issue has been resolved. Thank you for opening issue.
