### ISSUE TITLE
HDP 2.6.4 ERROR

### ISSUE THREAD

**Issue by kumarrrr** [hortonworks/data-tutorials#470]
HDP Installation : <Add tutorial name here>
Platform version: <HDP 2.6.4>
**Link to tutorial**: <Either a Hortonworks link or GitHub link works fine>

### Description of issue:
The deployment for OVF template with validation failed. As a workaround I have extracted and recompiled another OVA file and managed to deploy it successfully. 
Upon completion, it’s shown as ESX5.1 and cannot be manage with several options like POWER ON.
![inkedpic01_li](https://user-images.githubusercontent.com/20973871/37198551-a8fa6698-23b9-11e8-877c-9d841533963e.jpg)
![inkedpic02_li](https://user-images.githubusercontent.com/20973871/37198553-a9446a18-23b9-11e8-89ec-22547c0a1b00.jpg)
![inkedpic03_li](https://user-images.githubusercontent.com/20973871/37198554-a9909d5c-23b9-11e8-9246-13b58d1c37d3.jpg)

We are running on ESX6.5 on our ESX hosts.

**Comment by gdeleon5** [comment]
@kumarrrr I'm not sure where you got the OVF file? You should be getting the OVA file from the [Sandbox Download Page](https://hortonworks.com/downloads/#sandbox) and confirm the MD5 hash value matches the downloaded file.

For VMWare, the filename should be **HDP_2.6.4_vmware_01_02_2018_1325.ova**.
For VirtualBox, the filename should be **HDP_2.6.4_virtualbox_01_02_2018_1428.ova**

**Comment by kumarrrr** [comment]
Thank you we are trying to create a dummy env in our vmx server so tat we
can playaround & fully deploy in the production mode in our company,Thanks
for your help
Could you help me to get in touch with sales people.

My contact number :0065 90104204
cc to kumarnirmal.sg@gmail.com

**Comment by kumarrrr** [comment]
let me know what info is needed,using VMWARE ESX6.5 on esx hosts

**Comment by gdeleon5** [comment]
@kumarrrr Did you confirm the filename you downloaded was: **HDP_2.6.4_vmware_01_02_2018_1325.ova** and not having filetype **.ovf**?

Did you also verify the MD5 hash value?

**Comment by kumarrrr** [comment]
![md5](https://user-images.githubusercontent.com/20973871/37317105-f5eb9152-269d-11e8-8aba-9be2e40eae98.PNG)

Sorry there was a typo by my side,I reconfirmed that the MD5 hash value matches but the VM cannot start still,
Kindly find the attached image,
Thanks

**Comment by gdeleon5** [comment]
@kumarrrr excellent!

Can you now share some screen shots on how you're deploying the sandbox and intermediate steps of the process (VMWare splash page). You should be following instructions from the [Sandbox Deployment & Install Guide](https://hortonworks.com/tutorial/sandbox-deployment-and-install-guide/section/2/).

Thanks!

**Comment by kumarrrr** [comment]
The above proves there is no issue on the image provided by Horton works & even i tried on vmworkstation instead on VM esx,its wrking fine on workstation,
The issue regarding the VM-ESX had been raised to VMWare team,
There is no error from HW Dev Team

**Comment by gdeleon5** [comment]
Thanks for confirming this is a VMWare issue and not Hortonworks sandbox issue. Closing issue.

**Comment by kumarrrr** [comment]
From where I can learn real hands HW security?May be free or less charged
