### ISSUE TITLE
Deploy Docker  HDP Sandbox on Ubuntu Error

### ISSUE THREAD

**Issue by lbird0** [hortonworks/data-tutorials#471]
**Tutorial name**: Deploy Docker  HDP Sandbox on Ubuntu 16.04 LTS - 
**Platform version**: Hortonworks Data Platform (HDP®) 2.6.4 on Hortonworks Sandbox - Docker
**Link to tutorial**: https://fr.hortonworks.com/tutorial/sandbox-deployment-and-install-guide/section/3/

### Description of issue:
OS: Ubuntu 16.04 LTS
following each step of the deployment guide:
downloaded file: start-sandbox-hdp-standalone_2-6-4.sh.zip
extracted to : start-sandbox-hdp-standalone_2-6-4.sh
then command: sh start-sandbox-hdp-standalone_2-6-4.sh
Issue:
in the script output , never get the final "Started Hortonworks HDP container" log.
instead, get:
waiting for ambari services to start
................................................................................
.................................................................................
................... etc ... which never ends.

### Proposed fix (if any):
i don't know

**Comment by lbird0** [comment]
add infos:
Docker version: Docker version 17.12.1-ce, build 7390fc6
After download, md5sum start-sandbox-hdp-standalone_2-6-4.sh.zip
2c2cee0aafc71405b373f89eb9a988d7
OK.
docker stop sandbox-hdp works, but then 
docker start sandbox-hdp give the same behavior: starting never ends.

**Comment by gdeleon5** [comment]
@lbird0 This issue has been assigned and will soon be looked at.

On HDP 2.6.4, after you "docker stop", you will need to re-deploy sandbox using the **start-sandbox-hdp-standalone_2-6-4.sh** script.

**Comment by vineshcpaul** [comment]
@lbird0 

Tried deploying HDP 2.6.4 Sandbox on Ubuntu 16.04 LTS ( Docker version 17.12.1-ce)  and the deployment was successful.
Could you please check if the md5sum of the shell script (start-sandbox-hdp-standalone_2-6-4.sh ) used for deployment is 
b14f4538147851c51b26d9da37ab931c.
Also , please check if you have configured memory as per the recommendations.
https://hortonworks.com/tutorial/sandbox-deployment-and-install-guide/section/3/#configure-docker-memory

**Comment by lbird0** [comment]
@vineshcpaul 

Hi Vinesh,

Thank you for responding. checksum is ok. 

md5sum start-sandbox-hdp-standalone_2-6-4.sh
b14f4538147851c51b26d9da37ab931c  start-sandbox-hdp-standalone_2-6-4.sh

on https://hortonworks.com/tutorial/sandbox-deployment-and-install-guide/section/3/#configure-docker-memory
Recommendation for memory configuration says :

For Linux
No special configuration needed for Linux.

we found a workaround extracting the docker image inside the virtualbox sandbox and using this one.

**Comment by gdeleon5** [comment]
@vineshcpaul / @lbird0 Do we still need this issue opened?

**Comment by gdeleon5** [comment]
@lbird0 @vineshcpaul has this been resolved?

**Comment by lbird0** [comment]
Hi @gdeleon5 , you can close this thread.

**Comment by gdeleon5** [comment]
issue resolved
