### ISSUE TITLE
rainy, windy and foggy must be type int not boolean

### ISSUE THREAD

**Issue by eino-makitalo** [hortonworks/data-tutorials#496]
**Tutorial name**: <Add tutorial name here>
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**: <Either a Hortonworks link or GitHub link works fine>

### Description of issue:
windy, rainy and foggy must be int not boolean
### Proposed fix (if any):
I've got errror because Nifi and SAM do not modify windy, rainy and foggy but just send them forward.
In SAM the schema must be
{
 "type": "record",
 "namespace": "com.orendainx.hortonworks.trucking",
 "name": "TruckViolations",
 "fields": [
  {
   "name": "eventTime",
   "type": "long"
  },
  {
   "name": "routeId",
   "type": "int"
  },
  {
   "name": "congestionLevel",
   "type": "int"
  },
  {
   "name": "truckId",
   "type": "int"
  },
  {
   "name": "speed",
   "type": "int"
  },
  {
   "name": "eventType",
   "type": "string"
  },
  {
   "name": "windy",
   "type": "int"
  },
  {
   "name": "rainy",
   "type": "int"
  },
  {
   "name": "foggy",
   "type": "int"
  },
  {
   "name": "longitude",
   "type": "double"
  },
  {
   "name": "latitude",
   "type": "double"
  },
  {
   "name": "routeName",
   "type": "string"
  },
  {
   "name": "driverId",
   "type": "int"
  },
  {
   "name": "driverName",
   "type": "string"
  }
 ]
}

The error is in both truck_violations and truck_avg_speed

**Comment by gdeleon5** [comment]
@eino-makitalo Thanks for reporting issue. We are working on an HDF 3.1 refresh that will address some issues and schema changes. Please stand-by.

**Comment by Castro38** [comment]
@eino-makitalo Thank you for your patience. 

There is a new HDF 3.1.1 sandbox, you can download it [here](https://hortonworks.com/downloads/#sandbox). Also, our HDF tutorials have been updated, feel free to revisit our [SAM in Trucking IoT on HDF Tutorial](https://hortonworks.com/tutorial/sam-in-trucking-iot-on-hdf/).
