### ISSUE TITLE
Nifi installation via Ambari add service fails

### ISSUE THREAD

**Issue by rtheron** [hortonworks/data-tutorials#498]
**Tutorial name**: <Add tutorial name here>
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**: <Either a Hortonworks link or GitHub link works fine>

### Description of issue:
Nifi installation fails, it appears as if the hosted file that's downloaded for the install either doesn't exist or is zero'd out (it's a 0kb .tar.gz that ends up in the /tmp directory (/tmp/nifi-1.1.0.2.1.2.0-10-bin.tar.gz)

### Proposed fix (if any):

**Comment by Castro38** [comment]
@rtheron thank you for submitting this issue. Our team is working on making current the tutorials that require both HPD and HDF services concurrently. We appreciate your patience and feedback.

Thank you for your work around:
cd /tmp
wget https://archive.apache.org/dist/nifi/1.1.0/nifi-1.1.0-bin.tar.gz
mv nifi-1.1.0-bin.tar.gz nifi-1.1.0.2.1.2.0-10-bin.tar.gz

-->> install nifi via ambari

**Comment by Castro38** [comment]
@rtheron we have made some updates to both our HDF sandbox and tutorials that address the NiFi issue you were having. This  new sandbox release gives you the ability to spin up both the HDP and HDF sandboxes simultaneously so there is no need to install NiFi on the HDP sandbox. 

To download the latest HDF3.1.1 and HDP2.6.5 Sandboxes: [Hortonworks Downloads Page](https://hortonworks.com/downloads/#sandbox)

To updated HDF Tutorials: [Hortonworks HDF Tutorials](https://hortonworks.com/tutorials/?tab=product-hdf)

Thanks
