### ISSUE TITLE
Nifi AND Solr installation instructions no longer valid

### ISSUE THREAD

**Issue by rtheron** [hortonworks/data-tutorials#499]
**Tutorial name**: Real world examples developing with hadoop - social media
**Platform version**: HDP 2.6.5
**Link to tutorial**: https://hortonworks.com/tutorial/analyzing-social-media-and-customer-sentiment-with-apache-nifi-and-hdp-search/

### Description of issue:
Nifi install fails due to zero kb size installer tar.gz (incorrect download link during install process)

Solr installation instructions are no longer valid, installation simply fails, and if you then follow online guides to install via amber management pack it also fails because of the first attempted install via amber
### Proposed fix (if any):

**Comment by Castro38** [comment]
@rtheron thank you for submitting this issue. Our team is working on making current the tutorials that require both HPD and HDF services concurrently. Mean while this tutorial will be offline.  We appreciate your patience and feedback.

**Comment by james94** [comment]
@rtheron there will be a new version of this tutorial out soon that addresses the problem you mentioned. Thank you for your patience. I will share the link with you once the tutorial updates are published.

**Comment by james94** [comment]
@rtheron this tutorial will be redirected to a new tutorial series called "Building a Sentiment Analysis Application." This problem is addressed in that latest tutorial series.
