### ISSUE TITLE
Waiting for ambari services when deploying HDP sandbox 2.6.4 on Docker

### ISSUE THREAD

**Issue by yuhang-lin** [hortonworks/data-tutorials#501]
**Tutorial name**: Deploying Hortonworks Sandbox on Docker - Hortonworks
**Platform version**: HDP 2.6.4
**Link to tutorial**: https://fr.hortonworks.com/tutorial/sandbox-deployment-and-install-guide/section/3/

### Description of issue:
OS: Ubuntu 16.04 LTS
Docker version: 17.12
available memory for docker: 7.79 GB
run the command:
```sh start-sandbox-hdp-standalone_2-6-4.sh```
Issue:
in the script output , never get the final "Started Hortonworks HDP container" log.
instead, get:
waiting for ambari services to start
................................................................................
.................................................................................
................... etc ... for half an hour

**Comment by gdeleon5** [comment]
@yuhang-lin can you please provide entire script output?

**Comment by yuhang-lin** [comment]
Thank you. I uninstalled docker 17.12 and installed 17.09 then it worked. I think this issue can be closed.

**Comment by gdeleon5** [comment]
@yuhang-lin Thank you for reporting issue.
Soon to be announced... a new version of HDP and HDF will soon be available.
