### ISSUE TITLE
Zeppelin link not visible in Sandbox 2.6.4

### ISSUE THREAD

**Issue by Meister1867** [hortonworks/data-tutorials#502]
**Tutorial name**: <Add tutorial name here>
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**: <Either a Hortonworks link or GitHub link works fine>

### Description of issue:
When I view the tutorial for launching Zeppelin in the Sandbox it says "once you’re in Ambari just click the Views dropdown (upper-right corner) and select Zeppelin."  However, I do not see Zeppelin in the Views dropdown.

### Proposed fix (if any):
Investigate/Confirm.  I navigated to http://hdp264server:9995 and could see Zeppelin Notebooks there.

**Comment by gdeleon5** [comment]
issue resolved - thank you for reporting
