### ISSUE TITLE
Tutorial-830 cannot be completed with the HDF sandbox version 3.1.0

### ISSUE THREAD

**Issue by dwelden** [hortonworks/data-tutorials#515]
**Tutorial name**: Real-Time Event Processing In NiFi, SAM, Schema Registry and SuperSet
**Platform version**: HDF 3.1
**Link to tutorial**: https://hortonworks.com/tutorial/real-time-event-processing-in-nifi-sam-schema-registry-and-superset/

**Comment by gdeleon5** [comment]
@dwelden We've officially published new HDF 3.1.1 (and HDP 2.6.5) sandbox and tutorials have been updated. Please download latest sandbox and revisit tutorial.

[Hortonworks Downloads Page](https://hortonworks.com/downloads/#sandbox)
