### ISSUE TITLE
Hortonworks HDF Tutorial Link is not working

### ISSUE THREAD

**Issue by sajjad765** [hortonworks/data-tutorials#544]
**Tutorial name**: Analyzing Social Media and Customer Sentiment With Apache NiFi and HDP Searche
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**: <https://hortonworks.com/tutorial/analyzing-social-media-and-customer-sentiment-with-apache-nifi-and-hdp-search/>

**Comment by Castro38** [comment]
@sajjad765 thank you for reaching out to us. We are currently working on making this tutorial current to work with both **our new HDF3.1.1 and HDP2.6.5** sandboxes. As soon as it is updated we will share an update.

**Comment by james94** [comment]
@sajjad765 We will fix this broken link issue very soon. This tutorial link will be redirected to a new tutorial series called "Building a Sentiment Analysis Application".
