### ISSUE TITLE
Port Forwarding instructions wrong for HDP Sandbox 2.6.5

### ISSUE THREAD

**Issue by eric-b-richardson** [hortonworks/data-tutorials#557]
**Tutorial name**: Sandbox Port Forwarding Guide:Sandbox Port Forwarding on VirtualBox
**Platform version**: hdp 2.6.5 sandbox
**Link to tutorial**: https://hortonworks.com/tutorial/sandbox-port-forwarding-guide/section/1/

### Description of issue:
Tutorial says to SSH into the VM then edit the script that starts the container.
I installed a new Virtual Box HDP Sandbox 2.6.5 and followed the instructions but the start script does not exist.

```shell
$ ssh -p 2122 root@sandbox.hortonworks.com
root@sandbox.hortonworks.com's password: 
Last login: Wed Jul 11 22:09:40 2018 from 10.0.2.2
[root@sandbox-host ~]# ls -la /root/
total 44
dr-xr-x---.  3 root root 4096 Jul 11 22:08 .
dr-xr-xr-x. 19 root root 4096 Jun 26 08:14 ..
-rw-------.  1 root root 1750 Jun 26 07:57 anaconda-ks.cfg
-rw-------   1 root root  341 Jul 11 23:53 .bash_history
-rw-r--r--.  1 root root   18 Dec 29  2013 .bash_logout
-rw-r--r--.  1 root root  176 Dec 29  2013 .bash_profile
-rw-r--r--.  1 root root  176 Dec 29  2013 .bashrc
-rw-r--r--.  1 root root  100 Dec 29  2013 .cshrc
drwxr-----   3 root root 4096 Jun 26 08:11 .pki
-rw-r--r--.  1 root root  129 Dec 29  2013 .tcshrc
-rw-r--r--   1 root root    5 Jun 26 07:58 .vbox_version
```

As you can see the file `/root/start_scripts/start_sandbox.sh` does not exist.

In fact no file exists with the name start_sandbox.sh. Interestingly, there is a sandbox-start.sh in a different directory but it does not have the list of ports described in the tutorial.

```shell
[root@sandbox-host ~]# cd /
[root@sandbox-host /]# find -name 'start_sandbox.sh'
[root@sandbox-host /]# find -name 'sandbox-start.sh'
./sandbox/sandbox-start.sh
```

**Comment by gdeleon5** [comment]
@eric-b-richardson The "Sandbox Port Forwarding Guide" has been replaced with Sandbox Architecture (https://hortonworks.com/tutorial/sandbox-architecture/).

**Comment by krysal** [comment]
@gdeleon5 the link that you give is not a tutorial for adding ports to the HDP Sandbox 2.6.5, it provides an explanation of the new architecture, ok, but I think that this issue should be reopen since it's not solved.

Adding ports is an important step to connect software external (like GUIs) to the VM with programs installed whitin it, and it seems more complicated in the new version than in the Sandbox 2.6.4.

Please I beg for a simple tutorial to add port forwarding in the HDP Sandbox 2.6.5.

Thanks in advance for your help!

**Comment by Stankee** [comment]
Still waiting on a proper port forwarding guide for 2.6.5...

**Comment by Stankee** [comment]
@gdeleon5 
Thank you for re-opening the issue. I've downgraded 2.6.5 to 2.6.4 in order to be able to use the archived port forwarding guides. I opened port 7070 in Virtual Box and edited start_scripts/start_sandbox.sh and it works fine. How can I do that in 2.6.5? The question is really that simple, how can we add another port to be forwarded in the new sandbox architecture?

**Comment by vineshcpaul** [comment]
@Stankee @gdeleon5 
If you have HDP 2.6.5 VM deployed, there should be a file name generate-proxy-deploy-script.sh under /sandbox/deploy-scripts/assets. Please try editing the script to add a port that you want to forward. There are 2 arrays defined in the script, one is called tcpPortsHDP, add a new entry in the following format considering port 23232 as the one you need to forward.
[23232]=23232.
Once the change is made, rerun the script 
cd /sandbox/deploy-scripts
assets/generate-proxy-deploy-script.sh

This generate as new script proxy-deploy.sh under /sandbox/deploy-scripts/sandbox/proxy/proxy-deploy.sh

execute proxy-deploy.sh to get the new reverse proxy deployed.
cd /sandbox/deploy-scripts
sandbox/proxy/proxy-deploy.sh
Also, the port needs to be forwarded on the virtualbox as well . 
VirtualBox -> settings -> network -> Advanced -> port forwarding -> add new port forwarding rule

If you are using the docker version of the sandbox, then the same process applies, except the path, you will find the scripts in deploy_scripts folder under the following locations
deploy-scripts/assets/generate-proxy-deploy-script.sh

Before running docker-deploy-hdpX.sh , edit deploy-scripts/assets/generate-proxy-deploy-script.sh and make the necessary port forwarding changes.

**Comment by rguillome** [comment]
Hi,

I'm facing a similar problem with current sandbox-proxy : the Kafka listeners' default port (6667) is not exposed by the nginx front proxy : need to add 
```
server {
  listen 6667;
  server_name sandbox-hdp.hortonworks.com;
  location / {
    proxy_pass http://sandbox-hdp-security:6667;
  }
}
```
at the end of the /etc/nginx/conf.d/http-hdp.conf file

**Comment by gdeleon5** [comment]
Hi @rguillome ,
I verified on HDP 2.6.5 (VirtualBox) that port 6667 is opened. Please confirm.

**Verification 1**:
1. ssh -p 2200 root@sandbox-hdp.hortonworks.com
2. cat /sandbox/deploy-scripts/assets/generate-proxy-deploy-script.sh | grep 6667

**Verification 2**:
1. ssh -p 2200 root@sandbox-hdp.hortonworks.com
2. docker ps | grep 6667

**Comment by gdeleon5** [comment]
@Stankee @krysal ,

Please review instructions provided by @vineshcpaul. Let me know if they are helpful.

Thanks @vineshcpaul for providing instructions.

**Comment by krysal** [comment]
It worked for me :tada: Thank you @vineshcpaul!!

I had to connect with @gdeleon5's instructions ussing Putty because in the console of VirtualBox window I couldn't find the `/sandbox/deploy-scripts/...` folder (neither in web console).

Thanks for reopening the issue too @gdeleon5.

**Comment by nkanala** [comment]
I need to open up port 88 for kerberos authentication. I have HDP 2.6.5 on virtualbox and don't find the startup scripts. Unable to login using port 2200 either. Is there a way to open it up? I am using a bridged adapter and port forwarding is disabled in the network settings.

**Comment by PopescuStefanRadu** [comment]
I am using a docker image, I had added the port I want to expose in the 
``/sandbox/deploy-scripts/assets/generate-proxy-deploy-script.sh`` and ran ``/sandbox/deploy-scripts/docker-deploy-hdp265.sh`` however the proxy server exits with an error:
```
[root@sandbox-host proxy]# ./proxy-deploy.sh 
sandbox-proxy
2018/11/05 10:56:00 [emerg] 1#1: host not found in upstream "sandbox-hdp" in /etc/nginx/conf.d/http-hdp.conf:9
nginx: [emerg] host not found in upstream "sandbox-hdp" in /etc/nginx/conf.d/http-hdp.conf:9
```
Is there something I did wrong?

**Comment by vineshcpaul** [comment]
@PopescuStefanRadu 
After you made changes to generate-proxy-deploy-script.sh, you need to run the same script generate-proxy-deploy-script.sh which will generate a new proxy-deploy.sh.

Please refer to my [comment](https://github.com/hortonworks/data-tutorials/issues/557#issuecomment-432097658) above

**Comment by okmich** [comment]
Hi,

Having gone through the comments here, I still can't find the solution to this issue with 2.6.5.
I am the faculty of an online course on udemy and I used HDP 2.6.4 for the lab. In the course, we opened up a new port - 7070 and used it for Kylin on HDP. Now many students are reaching to find how to do same on 2.6.5.

I have checked the sandbox folder but there is not about deploy-scripts.
![image](https://user-images.githubusercontent.com/4775672/48412864-977fca80-e74e-11e8-8f54-01fe30e15c5f.png)

By the way, I am using the sandbox on Virtualbox.
Please kindly help.

Regards.

**Comment by vineshcpaul** [comment]
@okmich 
You are looking for the deploy scripts on the container. You need to be on the VM that is hosting the HDP container.
Your prompt says sandbox-hdp. The VM would be like this [root@sandbox-host ~]#

**Comment by gdeleon5** [comment]
It seems to me that all questions are answered.

**Any further questions or concerns?**

**Comment by LopezChris** [comment]
As per this GH issue, we have added instructions for custom port forwards on the Sandbox.
@eric-b-richardson Thank you for bringing up this issue, it helped us improve our tuitorials.

@gdeleon5 As this question has been answered I will close the issue, the instructions found in this issue are also found at the [learning the ropes tutorial](https://hortonworks.com/tutorial/learning-the-ropes-of-the-hortonworks-sandbox/#open-a-port-for-custom-use)

**Comment by pavel-sakun** [comment]
@gdeleon5 port 6667 specified in tcpPortsHDF so it doesn't get into conf.stream.d/tcp-hdp.conf as @rguillome mentioned above, but it gets into proxy port forward rules as both tcpPortsHDF and tcpPortsHDP are merged together while generating proxy-deploy.sh.
Adding [6667]=6667 to tcpPortsHDP resolves issue with conf.stream.d/tcp-hdp.conf but this will cause proxy-deploy.sh fail because of 6667 port specified twice.
Proposed solution:
- use different port number for kafka in HDF image, update tcpPortsHDF and tcpPortsHDP appropriately (same approach as for zookeeper)
or
- use either tcpPortsHDF or tcpPortsHDP while generating proxy-deploy.sh and update tcpPortsHDP with kafka port mapping

**Comment by eruiz** [comment]
Thanks all for this helpfully thread.

I tried your approach with HDP 3.0.1 on Hortonworks Sandbox, however _proxy-deploy.sh_ throws the error below:

```
[root@sandbox-host /]# pwd
/
[root@sandbox-host /]# sandbox/proxy/proxy-deploy.sh
d89d05a0ce279582b27a508d4e5ee565b98b21203d59f084ca379b05db84f9ce
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: 
starting container process caused "process_linux.go:402: container init 
caused \"rootfs_linux.go:58: mounting \\\"/assets/nginx.conf\\\" to rootfs 
\\\"/var/lib/docker/overlay2/38aebd025d181355ef31c32b28478ce8f8d464a6162d49d3a949e5161652d5cb/merged\\\" 
at 
\\\"/var/lib/docker/overlay2/38aebd025d181355ef31c32b28478ce8f8d464a6162d49d3a949e5161652d5cb/merged/etc/nginx/nginx.conf\\\" 
caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? 
Check if the specified host path exists and is the expected type.
```

Any help to solve this issue will be welcome.

Thanks

**Comment by TatanParker** [comment]
Friend, I think I found the solution for this trouble. Is related to the new architecture of HDP Sandbox (higher of 2.5 versions), please check my post in Cloudera:

https://community.cloudera.com/t5/Support-Questions/How-to-add-port-forwarding-in-HDP-Sandbox-2-6-5/m-p/287446/highlight/true#M213039
