### ISSUE TITLE
IoT Weather Station Hardware Kit BOM list is empty

### ISSUE THREAD

**Issue by ameetp** [hortonworks/data-tutorials#571]
**Tutorial name**: Analyze IoT Weather Station Data via Connected Data Architecture
**Platform version**: HDF 3.1.1
**Link to tutorial**: https://hortonworks.com/tutorial/analyze-iot-weather-station-data-via-connected-data-architecture/

### Description of issue:
The "IoT Weather Station Hardware Kit" BOM on Amazon is empty.

**Comment by gdeleon5** [comment]
Issue resolved - thank you for reporting
