### ISSUE TITLE
Table tpch_text2_orders are missing

### ISSUE THREAD

**Issue by aufschla** [hortonworks/data-tutorials#575]
**Tutorial name**: 6. Interactive SQL on Hadoop with Hive LLAP 
**Platform version**: 
== Sandbox Information ==
Platform: hdp-security
Build date: 06-18-2018
Ambari version: 2.6.2.0-155
Hadoop version: Hadoop 2.7.3.2.6.5.0-292
OS: CentOS Linux release 7.5.1804 (Core)
====

**Link to tutorial**: https://de.hortonworks.com/tutorial/interactive-sql-on-hadoop-with-hive-llap/

### Description of issue: After run the script datagen/datagen.sh 2 the table tpch_text2_orders are missing. Then I can't run the script datagen/load_data.sh, why this table are missing and the script is stop.

For the following steps oft the online training I need this table.

**Comment by gdeleon5** [comment]
@aufschla 
Thank you for reporting issue. Unfortunately, I was unable to recreate your issue.

Could you please provide output received for **sh -x datagen.sh 2** (notice -x option).

Just to make sure, you do meet tutorial memory requirements, right? 
**_allocate 11 GB RAM to the Sandbox virtual machine_** 

Can you also share which virtual machine you are using (virtualbox, vmware, docker)? Which operating system?

**Comment by gdeleon5** [comment]
@aufschla Please answer questions about to continue resolving your issue.

**Comment by gdeleon5** [comment]
closing issue. Did not receive additional information.
