### ISSUE TITLE
Unable to create a new service pool in SAM because UNKNOWN HOST sandbox-hdp.hortonworks.com

### ISSUE THREAD

**Issue by jwwallac** [hortonworks/data-tutorials#606]
**Tutorial name**: APPENDIX A: VISUALIZE TRUCKING DATA WITH SUPERSET VIA CDA
**Platform version**: <HDF 3.1.>
**Link to tutorial**: https://hortonworks.com/tutorial/real-time-event-processing-in-nifi-sam-schema-registry-and-superset/

### Description of issue:

I've 2 systems: a windows 10 system & linux ubuntu LTS 16.04. Each system has there own virtualbox VM on it. The Windows system has HDF and the Linux has HDP 2.6.5. I've updated their network settings to bridged and their respective host files and I'm able to successfully bring up shell in the box to the respective systems without issue by using the respective host names identified in the file. 

When I get to the the following step: 

1. Hover over the wrench to open the Configuration dropdown, select Service Pool, so we can add a new service pool for HDP.

In the field to the left of AUTO ADD, include the following:

http://sandbox-hdp.hortonworks.com:8080/api/v1/clusters/Sandbox

The function fails with an error, stating that sandbox-hdp.hortonworks.com is unknown. If I put in the IP address of the HDP VM it goes a little further, but again fails with an a different unknown host: sandbox-hdp-security. 

I found several references that CDA has been changed and that the directions need to be updated. Additionally, it asked me to run a script that wasn't there any longer. 

I'm unsure how to fix this issue. Please help.

**Comment by Castro38** [comment]
Hi @jwwallac,

Thank you for sharing your issue with us. 

Try using user:admin instead of user:raj_ops, you may need to change the password. Here is a link on how to do this [Learning the Ropes of the Hortonworks Sandbox:Admin Password Reset](https://hortonworks.com/tutorial/learning-the-ropes-of-the-hortonworks-sandbox/#admin-password-reset). Then re-try the following step:


Let me know if this works.

**Comment by jwwallac** [comment]
I had previously verified that "raj_ops" and his default password was working by logging in  successfully to ambari. 

I abandoned the virtualbox setup and went the docker installation route on the same system. Hopefully, I'll have more success. 

Thanks.
