### ISSUE TITLE
Add Bullet Point covers Amount of Time to Complete Tutorial 

### ISSUE THREAD

**Issue by james94** [hortonworks/data-tutorials#61]
Please Fill in the Following Information before submitting your Issue:

**Tutorial Name**: All Tutorials
**HDP Version are you Running**: 2.4
**Applicable HDP Components**: Sandbox

**Link to tutorial**(Hortonworks or GitHub website):
### Detailed Description of Issue:

Users are not sure how long they will spend in the tutorial, we should add a bullet point in the pre-requisite or outline section that gives them a clear statement on this.
### Proposed Fix:

Add a bullet point to the outline section that tells the user how long the tutorial will take.
@ZacBlanco 
@roberthryniewicz

**Comment by orendain** [comment]
Committers discussed this and other structure changes to tutorials.  It resulted in a new suggested tutorial template.  Closing this issue since it's been resolved.
