### ISSUE TITLE
I can't able to save Schema... SAVE is not working

### ISSUE THREAD

**Issue by hprasanthms** [hortonworks/data-tutorials#614]
**Tutorial name**: <Add tutorial name here>
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**: <Either a Hortonworks link or GitHub link works fine>

**Comment by Castro38** [comment]
Hi @hprasanthms, can you please provide the name of the tutorial in which you are having issues saving the Schema in?

Thanks

**Comment by Castro38** [comment]
Hi @hprasanthms, closing issue. If you are still having issue please open a new issue and provide details. 

Thank you!
