### ISSUE TITLE
Sandbox Port Forwarding Guide redirects

### ISSUE THREAD

**Issue by Meister1867** [hortonworks/data-tutorials#652]
**Tutorial name**: <Add tutorial name here>
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**: <Either a Hortonworks link or GitHub link works fine>

### Description of issue:
The Sandbox Port Forwarding Guide (https://hortonworks.com/tutorial/sandbox-port-forwarding-guide/) link redirects to Sandbox Architecture (https://hortonworks.com/tutorial/sandbox-architecture/).  Although the content may be related, it doesn't give a guide of how to open ports or do port forwarding as is implied by other literature. 

### Proposed fix (if any):
Provide information on Port Forwarding.

**Comment by LopezChris** [comment]
Hello,

You are correct, the Sandbox port forwarding guide has been deprecated. Starting in HDP 2.6.5 and HDF 3.1.1 we are no longer able to open ports like the old tutorial indicated that is why it has been deprecated. In the new architecture a reverse proxy is used to open and redirect ports in the Sandbox.
If you are using a Sandbox that older than HDP 2.6.5 and HDF 3.1.1 you may find the port forwarding guide on this github repository under the [HDP2.6 archive](https://github.com/hortonworks/data-tutorials/tree/archive-hdp-2.5/tutorials/hdp/hdp-2.6/sandbox-port-forwarding-guide). 
Here is the archived tutorial:
- [Port Forwarding on Virtual Box](https://github.com/hortonworks/data-tutorials/blob/archive-hdp-2.5/tutorials/hdp/hdp-2.6/sandbox-port-forwarding-guide/tutorial-1.md)
- [Port Forwarding on VMWare](https://github.com/hortonworks/data-tutorials/blob/archive-hdp-2.5/tutorials/hdp/hdp-2.6/sandbox-port-forwarding-guide/tutorial-2.md).
- [Port Forwarding on native Docker](https://github.com/hortonworks/data-tutorials/blob/archive-hdp-2.5/tutorials/hdp/hdp-2.6/sandbox-port-forwarding-guide/tutorial-3.md).
- [Port Forwarding on Azure](https://github.com/hortonworks/data-tutorials/blob/archive-hdp-2.5/tutorials/hdp/hdp-2.6/sandbox-port-forwarding-guide/tutorial-4.md).

Thank you for asking this question, I am sure it will help others.
