### ISSUE TITLE
CSV gets deleted without writing to my new table

### ISSUE THREAD

**Issue by jmcd16** [hortonworks/data-tutorials#718]
**Tutorial name**: How to Process Data with Apache Hive
**Platform version**:  2.6.2.0 
**Link to tutorial**: https://hortonworks.com/tutorial/how-to-process-data-with-apache-hive/

### Description of issue:
I can't get passed step 3.3. 
When I use the command: 
LOAD DATA INPATH '/user/maria_dev/drivers.csv' OVERWRITE INTO TABLE temp_drivers;
The csv is indeed deleted, but my temp_drivers table is still empty.

**Comment by gdeleon5** [comment]
@jmcd16,
Thanks for reporting issue - I will take a look and get back to you.

**Comment by jmcd16** [comment]
Thanks, Gdeleon5. But I think this is likely a user error issue.
