### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by egarat** [hortonworks/data-tutorials#721]
**Tutorial name**: Analyzing Social Media and Customer Sentiment With Apache NiFi and HDP Search
**Platform version**: n/a
**Link to tutorial**: https://hortonworks.com/tutorial/analyzing-social-media-and-customer-sentiment-with-apache-nifi-and-hdp-search/

### Description of issue:
Not sure if this is the right place to report, but the link to this tutorial does not work properly. Instead, it redirects to this tutorial: https://de.hortonworks.com/tutorial/analyze-transit-patterns-with-apache-nifi/

**Comment by gdeleon5** [comment]
@egarat,
Thank you for reporting issue.

This tutorial is being updated and replaced with a different tutorial, which is not available on website at this time - this is why you are getting redirected.
