### ISSUE TITLE
Issue while pulling pull hortonworks/sandbox-hdp:2.6.5 

### ISSUE THREAD

**Issue by guptamanoj61** [hortonworks/data-tutorials#724]
**Tutorial name**: <Add tutorial name here>
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**: <Either a Hortonworks link or GitHub link works fine>

### Description of issue:
[root@hdp HDP_2.6.5_deploy-scripts_180624d542a25]# docker pull hortonworks/sandbox-hdp:2.6.5
2.6.5: Pulling from hortonworks/sandbox-hdp
9770d73ca513: Pull complete
cbba75ae30cd: Pull complete
283e5725c5f6: Pull complete
1426e9ece03d: Pull complete
4b00051fa827: Pull complete
d09cdd825ed6: Pull complete
dcbfe1670fa6: Pull complete
fd78a46757f7: Pull complete
5bad1882139b: Pull complete
d29a62d4eb22: Pull complete
4fb93bf04f14: Pull complete
8827f466ab83: Pull complete
a0fc39e77949: Pull complete
595eabd2c628: Pull complete
2a7fd016935e: Pull complete
87526fe8ce7c: Pull complete
d91a044a9aaf: Pull complete
bbffcb08266c: Pull complete
65c812fb262a: Pull complete
132f30914412: Pull complete
0f3e10681220: Pull complete
505f5a3365a7: Pull complete
abaff3c0f761: Pull complete
7d75f267b911: Pull complete
18099674493a: Pull complete
26310ba15287: Pull complete
635c5bfe7fc8: Pull complete
2f80a5abf101: Extracting [==================================================>]  7.041GB/7.041GB
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /kafka-logs/__consumer_offsets-33/00000000000000000000.index: no space left on device
[root@hdp HDP_2.6.5_deploy-scripts_180624d542a25]#

**Comment by gdeleon5** [comment]
@guptamanoj61,

Looking at your prompt,  **[root@hdp**, it seems to me that you're running command from within the Sandbox, which is incorrect. 

Please follow directions using [Sandbox Deployment and Install Guide](https://hortonworks.com/tutorial/sandbox-deployment-and-install-guide/).

Which operating system are you using?

**Comment by thammuio** [comment]
I am running into the same issue; even though enough free space is there...

**Comment by gdeleon5** [comment]
@thammuio 
Which OS are you running?
Also, please provide output showing errors.

**Comment by thammuio** [comment]
@gdeleon5 I got it resolved by 

1. Mounting /var/lib/docker as a mount with ample disk space
2. Increasing docker storage option (dockerd --storage-opt dm.basesize=100G)

**Comment by gdeleon5** [comment]
@thammuio That's great! I'm glad you resolved the issue and shared the solution.
