### ISSUE TITLE
data naming standards are nice - when used

### ISSUE THREAD

**Issue by kazsulec** [hortonworks/data-tutorials#734]
**Tutorial name**: Hadoop Tutorial – Getting Started with HDP
**Platform version**: HDP 2.65
**Link to tutorial**: https://hortonworks.com/tutorial/hadoop-tutorial-getting-started-with-hdp/section/3/
### Description of issue:
Tables in tutorial are named using underscore to separate words. Mostly. "truck_mileage", "avg_mileage", .. then "drivermileage".  It's a good practice to be consistent in such naming.

### Proposed fix (if any): Rename "drivermileage" to "driver_mileage".  Or drop the use of underscores altogether in table names.

A similar issue exists with table column names, but there underscores are mostly absent except for the months' mileage and gas values. Again, a consistent naming standard is preferred.

**Comment by LopezChris** [comment]
Thank you for pointing this out. Will fix inconsistencies soon.

**Comment by LopezChris** [comment]
https://github.com/hortonworks/data-tutorials/pull/774
Issue addressed.
