### ISSUE TITLE
row__id.transactionid -> row__id.writeid?

### ISSUE THREAD

**Issue by kazsulec** [hortonworks/data-tutorials#767]
**Tutorial name**: Using Hive ACID Transactions to Insert, Update and Delete
**Platform version**: HDP 3.0.1
**Link to tutorial**: https://hortonworks.com/tutorial/using-hive-acid-transactions-to-insert-update-and-delete-data/
### Description of issue:
Appears transactionid has changed to writeid, at least in the 3.0.1 sandbox I downloaded today. No doubt doco needs to catch up.

                                                                               
Beeline version 3.1.0.3.0.1.0-187 by Apache Hive                                                                                 
0: jdbc:hive2://localhost:10000> select row__id from hello_acid;                                                                 
INFO  : Compiling command(queryId=hive_20181206000808_40fe5594-364f-43d7-979b-832f28dbb8df): select row__id from hello_acid      
INFO  : Semantic Analysis Completed (retrial = false)                                                                            
INFO  : Returning Hive schema: Schema(fieldSchemas:[FieldSchema(name:row__id, type:struct<writeid:bigint,bucketid:int,rowid:bigin
t>, comment:null)], properties:null)                                                                                             
INFO  : Completed compiling command(queryId=hive_20181206000808_40fe5594-364f-43d7-979b-832f28dbb8df); Time taken: 0.2 seconds   
INFO  : Executing command(queryId=hive_20181206000808_40fe5594-364f-43d7-979b-832f28dbb8df): select row__id from hello_acid      
INFO  : Completed executing command(queryId=hive_20181206000808_40fe5594-364f-43d7-979b-832f28dbb8df); Time taken: 0.008 seconds 
INFO  : OK                                                                                                                       
+-----------------------------------------------+                                                                                
|                    row__id                    |                                                                                
+-----------------------------------------------+                                                                                
| {"writeid":1,"bucketid":536936448,"rowid":0}  |                                                                                
| {"writeid":5,"bucketid":537001984,"rowid":0}  |                                                                                
+-----------------------------------------------+                                                                                
2 rows selected (0.535 seconds)                                                                                                  
0: jdbc:hive2://localhost:10000> set hive.optimize.ppd=false;

**Comment by gdeleon5** [comment]
@kazsulec  Thank you for reporting issue
