### ISSUE TITLE
Please update content

### ISSUE THREAD

**Issue by emceemouli** [hortonworks/data-tutorials#769]
**Tutorial name**: <Add tutorial name here>
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**: <Either a Hortonworks link or GitHub link works fine>

**Comment by gdeleon5** [comment]
@emceemouli Which tutorial or you referring to? Could you please provide references or content?

**Comment by LopezChris** [comment]
@emceemouli 
I see that you have tagged HDP2.6 and HDF2.2, we have recently updated to HDP3.0.1 perhaps the content that you need is on our archive.

Archived tutorials can be found [here](https://github.com/hortonworks/data-tutorials/tree/archive-hdp265-hdf311/tutorials) under the **archive-hdp265-hdf311** branch.

Please let us know if this addressed your issue or please provide further information.

Thank you.

**Comment by LopezChris** [comment]
closing issue as no further information is provided, if this continues to be an issue please re-open.
