### ISSUE TITLE
No sh interpreter in zeppelin

### ISSUE THREAD

**Issue by harrysingh89** [hortonworks/data-tutorials#772]
**Tutorial name**: Querying Data from Druid
**Platform version**: HDP 3.0.1
**Link to tutorial**: https://hortonworks.com/tutorial/getting-started-with-druid/section/4/

**Comment by LopezChris** [comment]
@harrysingh89 
Here is how to add a shell interpreter to the Sandbox,
1. Click on anonymous which is located on the right hand side of the Zeppelin Welcome page
2. On the drop down select Interpreter
3. On the right hand corner of the Interpreters page you will see Create, click on it

This will bring up the Create new interpreter option. We will use the shell interpreter as an example.

4. Type sh in the Interpreter Name box
5. Type sh in the Interpreter Group as well
6. Click on Save

[Instructions for adding shell interpreter here](https://hortonworks.com/tutorial/getting-started-with-apache-zeppelin/#creating-an-interpreter)

Once you have added the interpreter ensure that it is [binded to the note that you are working on](https://hortonworks.com/tutorial/getting-started-with-apache-zeppelin/#binding-an-interpreter)
