### ISSUE TITLE
wrong query for temp_timesheet table

### ISSUE THREAD

**Issue by devwebcl** [hortonworks/data-tutorials#773]
**Tutorial name**: How to Process Data with Apache Hive
**Platform version**: HDP 3.0.1
**Link to tutorial**: https://hortonworks.com/tutorial/how-to-process-data-with-apache-hive/

### Description of issue:
wrong query for temp_timesheet table:
SELECT * FROM timesheet LIMIT 10

### Proposed fix (if any):
SELECT * FROM temp_timesheet LIMIT 10

**Comment by LopezChris** [comment]
@devwebcl You are correct, thank you for pointing it out, I will make the change.
