### ISSUE TITLE
Data tutorial page does not exist.

### ISSUE THREAD

**Issue by busrat** [hortonworks/data-tutorials#775]
**Tutorial name**: <Building a Sentiment Analysis Application>
**Platform version**: <HDP 3.1.0, HDF, etc.>
**Link to tutorial**: <https://hortonworks.com/tutorial/building-a-sentiment-analysis-application/>

**Comment by LopezChris** [comment]
https://github.com/hortonworks/data-tutorials/pull/776
Solves this issue.

Please replace that line of code with this one:
```
sudo -u hdfs wget https://github.com/hortonworks/data-tutorials/raw/master/tutorials/cda/building-a-sentiment-analysis-application/application/setup/data/tweets.zip -O $LFS_TWEETS_PACKAGED_PATH/tweets.zip
```
Please let us know if this fixed your issue.

**Comment by LopezChris** [comment]
Verified link is now good. Closing issue.

Thank you.
