### ISSUE TITLE
Data Analytics Studio webapp not starting

### ISSUE THREAD

**Issue by cyberoner1** [hortonworks/data-tutorials#778]
**Tutorial name**: Hadoop Tutorial – Getting Started with HDP
Hive - Data ETL
**Platform version**: <HDP 3.0.>
**Link to tutorial**: https://de.hortonworks.com/tutorial/hadoop-tutorial-getting-started-with-hdp/section/3/

### Description of issue:
When I want to open the webapp a new site opens with the adress: http://sandbox-hdp.hortonworks.com:30800/
Then I see:

The page cannot be displayed
--
The page you are looking for is currently unavailable. The Web site might be experiencing technical difficulties, or you may need to adjust your browser settings.
Please try the following:If you typed the page address in the Address bar, make sure that it is spelled correctly.If you are trying to reach a secure site, make sure your Security settings can support it.Click the Back button to try another link.DNS Fail

**Comment by gdeleon5** [comment]
@cyberoner1 
This seems to be a setup issue. Can you confirm that you can access the following URLs:
http://sandbox-hdp.hortonworks.com:4200
http://sandbox-hdp.hortonworks.com:1080
http://sandbox-hdp.hortonworks.com:8080

If not, please review [Learning the Ropes of the HDP Sandbox, Environment Setup](https://hortonworks.com/tutorial/learning-the-ropes-of-the-hortonworks-sandbox/#environment-setup)

**Comment by cyberoner1** [comment]
Hi, just found the problem. 
http://sandbox-hdp.hortonworks.com:4200 is working fine.
When I use localhost instead of http://sandbox-hdp.hortonworks.com it si working, too. So it looks like there is something wrong with my host
