### ISSUE TITLE
Add the wrong value at Value Separator

### ISSUE THREAD

**Issue by RaymondCui21** [hortonworks/data-tutorials#779]
**Tutorial name**: NiFi in Trucking IoT on HDF
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**: <Either a Hortonworks link or GitHub link works fine>

### Description of issue:

 Value Separator of CSVReader – Traffic Data and CSVReader – Enriched Truck Data should be '|' , not ',' . 
In the template, Properties Tab of these two Controller Services are:   Value Separator: '|'

### Proposed fix (if any):
Change the values to |

**Comment by james94** [comment]
@RaymondCui21,

Thank you for reporting the issue. You are absolutely correct. Would you like to contribute to the community by adding the solution and the team will verify?

Thanks,
James

**Comment by james94** [comment]
@RaymondCui21,

Just curious, would you like to contribute to the community by adding your suggested solution?

Thanks,
James

**Comment by RaymondCui21** [comment]
Hi James,

Sorry for late reply. I did not check my email. Yes, I'd like to. Please let me know how to contribute the community. 

Kind regards,
Raymond

**Comment by james94** [comment]
Hi @RaymondCui21,

Awesome! 

1. Fork our github repo: `https://github.com/hortonworks/data-tutorials`
2. Clone your forked github repo

3. Go to `NiFi in Trucking IoT on HDF` tutorial, correct the issue in the tutorial. 
4. Then `git add "[the path to the file being fixed]"`
5. `git commit -m "[summary of your potential solution"`
6. Finally push the changes to your forked repo. Ex: `git push origin master`
7. Go to github and create a pull request to master repo 

Let us know if you have any further questions.

**Comment by LopezChris** [comment]
@RaymondCui21 @james94 one last chance before I make the change and commit it :)

**Comment by RaymondCui21** [comment]
> @RaymondCui21 @james94 one last chance before I make the change and commit it :)

I checked the file  \nifi-in-trucking-iot-on-hdf\tutorial-3.md and found the issue is fixed. However, this issue on the webpage (https://hortonworks.com/tutorial/nifi-in-trucking-iot-on-hdf/section/3/) is not updated.

**Comment by gdeleon5** [comment]
@RaymondCui21 Under which branch did you see the issue resolved?

@james94 Can you please follow-up?

**Comment by james94** [comment]
@RaymondCui21, after looking on our **master, dev branch** in regard to **CSVReader – Traffic Data** and **CSVReader – Enriched Truck Data**, the value separator contains "`". What github branch were you on?

Dev Branch: https://github.com/hortonworks/data-tutorials/blob/dev/tutorials/hdf/nifi-trucking-iot-on-hdf/tutorial-3.md

Master Branch: https://github.com/hortonworks/data-tutorials/blob/master/tutorials/hdf/nifi-in-trucking-iot-on-hdf/tutorial-3.md

**Comment by LopezChris** [comment]
@james94 @RaymondCui21 we just needed an escape character :) closing now.
https://github.com/hortonworks/data-tutorials/pull/797
