### ISSUE TITLE
I couldn't to execute Hive query command line. I got the following error: INFO  : Tez session hasn't been created yet. Opening session ERROR : Failed to execute tez graph.  Please Help!  Due date will be to night!  Thanks!

### ISSUE THREAD

**Issue by gsebehat** [hortonworks/data-tutorials#781]
**Tutorial name**: <Add tutorial name here>
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**: <Either a Hortonworks link or GitHub link works fine>

**Comment by gdeleon5** [comment]
@gsebehat,
Can you please share which tutorial you are having trouble with?
Which sandbox are you using (i.e. HDP/HDF and version)?
Which environment (i.e Docker, VirtualBox, VMWare, Windows, macOS, Linux)?

**Comment by gdeleon5** [comment]
@gsebehat , closing issue for now. Please re-open when you are able to provide more information.
