### ISSUE TITLE
Zeppelin: Hands-on tour of notebooks doesn't enable visualizations

### ISSUE THREAD

**Issue by alv1234** [hortonworks/data-tutorials#787]
**Tutorial name**: Getting Started with HDP
**Platform version**: HDP 3.0
**Link to tutorial**: https://hortonworks.com/tutorial/hadoop-tutorial-getting-started-with-hdp/section/5/

### Description of issue:
After running this query, there are no visualization options beneath the query. The screenshots looks from a different zeppelin version (this one is v0.8.0)

`%spark2
val hiveContext = new org.apache.spark.sql.SparkSession.Builder().getOrCreate()
val riskFactorDataFrame = spark.read.format("csv").option("header", "true").load("hdfs:///tmp/data/riskfactor.csv")
riskFactorDataFrame.createOrReplaceTempView("riskfactor")
hiveContext.sql("SELECT * FROM riskfactor LIMIT 15").show()`

### Proposed fix (if any):
Replace instructions with using spark sql interpreter to query temporary table. then it works.

**Comment by LopezChris** [comment]
Hi @alv1234,

You are absolutely right. [PR 789](https://github.com/hortonworks/data-tutorials/pull/789) implements your proposed fix.

Thank you
