### ISSUE TITLE
HDP Sandbox - HDFS error (port 50070 not working)

### ISSUE THREAD

**Issue by anildub** [hortonworks/data-tutorials#790]
**Tutorial name**: <Add tutorial name here>
**Platform version**: <HDP 2.6, HDF 2.2, etc.>
**Link to tutorial**: <Either a Hortonworks link or GitHub link works fine>

**Comment by anildub** [comment]
I downloaded latest version of Hortonworks Sandbox 3.01 for VirtualBox and installed it as an appliance. HDFS server fails to start. When I looked at the log it says
 sandbox-hdp.hortonworks.com:50070: Connection refused (Connection refused).
I see that HDFS service is not running. netstat -tnspl | grep 50070 results in nothing.

**Comment by LopezChris** [comment]
Hello, I am just checking if you still had any issues. I deployed a fresh system to see if could reproduce but was unable to. 
I am using VirtualBox Version 5.2.18 r124319 (Qt5.6.2) on Windows 10 and am able to use the Sandbox just fine.

~~~
cfarnes@HW-DB2 MINGW64 ~
$ netstat -an | grep 50070
  TCP    127.0.0.1:50070        0.0.0.0:0              LISTENING
~~~

**Comment by anildub** [comment]
Problem was resolved after I enabled Virtualization in BIOS.

**Comment by LopezChris** [comment]
Awesome :) closing now.
