### ISSUE TITLE
Python interpreter configuration for Zeppelin does not persist when service is restarted

### ISSUE THREAD

**Issue by genemishchenko** [hortonworks/data-tutorials#791]
**Tutorial name**: Getting Started with Apache Zeppelin
**Platform version**: HDP 3.0.1
**Link to tutorial**: https://hortonworks.com/tutorial/getting-started-with-apache-zeppelin/#creating-an-interpreter

### Steps Leading to the Issue

(1) Ran the below command to install the "community managed" Python interpreter, as documented in the tutorial:

`[root@sandbox-hdp ~]# /usr/hdp/3.0.1.0-187/zeppelin/bin/install-interpreter.sh -n python`

(2) Followed the post-installation steps 1-3 successfully, as directed:
 ----1. Restart Zeppelin
 ----2. Create interpreter setting in 'Interpreter' menu on Zeppelin GUI
 ----3. Then you can bind the interpreter on your note

### Symptoms

The Python interpreter configuration created via Zeppelin UI does not persist across Zeppelin service restarts.

The HDFS configuration file /user/zeppelin/conf/interpreter.json is updated via the UI, but the changes are reverted upon Zeppelin restart.

The local file /etc/zeppelin/conf/interpreter.json is never updated.

*Additional Information*
- I have submitted another issue that should be assumed to be independent for now - #792.
- "Using Apache Zeppelin" section on docs.hortonworks.com does not have a sub-section for installing and using a new interpreter.

**Comment by LopezChris** [comment]
Hello,
You are correct about this issue as well. I am looking to see if I can find a solution to this issue

**Comment by LopezChris** [comment]
For now the workaround is to simply add the interpreter if Zeppelin restarts. A fix for this issue will be incorporated into future sandbox releases.
