### ISSUE TITLE
Newly installed Python interpreter for Zeppelin does not work

### ISSUE THREAD

**Issue by genemishchenko** [hortonworks/data-tutorials#792]
**Tutorial name**: Getting Started with Apache Zeppelin
**Platform version**: HDP 3.0.1
**Link to tutorial**: https://hortonworks.com/tutorial/getting-started-with-apache-zeppelin/

### Steps Leading to the Issue

(1) Ran the below command to install the "community managed" Python interpreter, as documented in the tutorial:

`[root@sandbox-hdp ~]# /usr/hdp/3.0.1.0-187/zeppelin/bin/install-interpreter.sh -n python`

(2) Followed the post-installation steps 1-3 successfully, as directed:

>  1. Restart Zeppelin
>  2. Create interpreter setting in 'Interpreter' menu on Zeppelin GUI
>  3. Then you can bind the interpreter on your note

### Symptoms

All the %python interpreter statements fail, even the simplest ones, e.g.:
`%python`
`print("test")`

The error:
> Traceback (most recent call last):
>   File "/tmp/zeppelin_python-2604294612768410068.py", line 20, in <module>
>     from py4j.java_gateway import java_import, JavaGateway, GatewayClient
> ImportError: No module named py4j.java_gateway

After this the interpreter does not respond.

Checked the "zeppelin.interpreters" property value in the local file /usr/hdp/current/zeppelin-server/conf/zeppelin-site.xml - none of the Python interpreter classes are listed there.

*Additional Information*
- I have submitted another issue that should be assumed to be independent for now - #791.
- "Using Apache Zeppelin" section on docs.hortonworks.com does not have a sub-section for installing and using a new interpreter.

**Comment by LopezChris** [comment]
@genemishchenko 
Just tried it out on a fresh system, and I have the same issue. Looking into this to find a solution.

**Comment by LopezChris** [comment]
It seems that there the library `py4j` is missing from the Sandbox, the solution was to install it and restart zeppelin.

~~~bash
yum -y update                                                                                                                                                                                                                                                      
yum install -y python-pip                                                                                                                                                                                                                                                 
pip install py4j                                                                                                                                                                                                                                                   
~~~
